### ISSUE TITLE
Add proper unit tests

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_swift#1]
Right now the only we have to test the rules is to build the contents of the `examples` directory. Our experience from `rules_apple` is that the integration shell tests are both slow and flaky, so we'd like to avoid using that approach (except, perhaps, in some isolated cases).

Instead, lets use the action-based analysis-time testing APIs in Skylark to verify the behavior of the rules without actually executing the actions. This should be significantly faster.

**Comment by keith** [comment]
It would be great if we could add some of these. I'm seeing some regressions with the last source dump that it would be nice to guard against in the future.

**Comment by keith** [comment]
`test/` now has these
