### ISSUE TITLE
`universal_protoc` fails to build

### ISSUE THREAD

**Issue by pennig** [bazelbuild/rules_swift#1037]
Running `bazel build //tools/protoc_wrapper:universal_protoc` fails with the same error as #762. Building other `universal_binary` targets in this repo do not fail. 

In the linked issue, the solution was to provide a platform mapping. Would the correct place for that platform mapping be `rules_swift` (here) or `protobuf` (where the `cc_library` for `protoc` is defined)? Seems that it'd be the responsibility of either of these to implement this, instead of forcing any consumer of `swift_proto_library` using `universal_tools` to implement their own platform mapping for `protoc`

**Comment by keith** [comment]
The problem is you cannot provide a platform mapping from a rules repo. It has to be at the root of your repo or a local path with `--platform_mappings`
