### ISSUE TITLE
swift_binary crashes on linux when compiled with bazel but not swift build

### ISSUE THREAD

**Issue by AttilaTheFun** [bazelbuild/rules_swift#1059]
Hey folks! I've been trying to find the source of an issue with swift_binaries built with rules_swift which segfault on linux but don't when build with swift build. The same binaries work correctly on both build systems on macOS.

The crash looks like:
```
ubuntu@focal:~/swift_atomics_test$ lldb bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
(lldb) target create "bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest"
Current executable set to '/home/ubuntu/swift_atomics_test/bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest' (aarch64).
(lldb) r
Process 85281 launched: '/home/ubuntu/swift_atomics_test/bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest' (aarch64)
before atomic
Process 85281 stopped
* thread #1, name = 'SwiftAtomicsTes', stop reason = signal SIGSEGV: invalid address (fault address: 0x18)
    frame #0: 0x0000aaaaaaac3ff4 SwiftAtomicsTest`ManagedAtomic.__allocating_init(_:) at ManagedAtomic.swift:0
   3   	
   4   	  internal var _storage: Value
   5   	
-> 6   	  public init(_ value: Value) {
   7   	    _storage = value
   8   	  }
   9   	}
Note: this address is compiler-generated code in function Atomics.ManagedAtomic.__allocating_init(τ_0_0) -> Atomics.ManagedAtomic<τ_0_0> that has no source code associated with it.
Target 0: (SwiftAtomicsTest) stopped.
```

I encountered this issue when trying to update rules_swift's grpc-swift to a newer version that pulls in swift-atomics.

I created a demo project by forking swift-atomics, making a tiny binary that reproduced the issue, and then stripping out code until it had only the minimum necessary to reproduce the issue:
https://github.com/AttilaTheFun/swift_atomics_test

It's actually trivial to reproduce. You just need two targets, a swift_library and a swift_binary. The swift library contains three files:

AtomicValue.swift
```
public protocol AtomicValue {
}
```

AtomicBool.swift
```
extension Bool: AtomicValue {
}
```

ManagedAtomic.swift
```
public class ManagedAtomic<Value: AtomicValue> {
  internal var _storage: Value

  public init(_ value: Value) {
    _storage = value
  }
}
```

And the swift binary has just one file:

SwiftAtomicsTest.swift
```
import Atomics

@main
struct SwiftAtomicsTestMain {
  static func main() throws {
    print("before atomic")

    let managedAtomic = ManagedAtomic(false)

    print("after atomic")
  }
}
```

The issue manifests on linux when the binary logs "before atomic" and then segfaults on the managedAtomic line:
```
ubuntu@focal:~/swift_atomics_test$ bazelisk run -s --compilation_mode=dbg --sandbox_debug //Sources/SwiftAtomicsTest
INFO: Analyzed target //Sources/SwiftAtomicsTest:SwiftAtomicsTest (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //Sources/SwiftAtomicsTest:SwiftAtomicsTest up-to-date:
  bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest
INFO: Elapsed time: 0.113s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest
before atomic
ubuntu@focal:~/swift_atomics_test$ 
```

But you can see here that the same code builds and runs fine with swift build:
```
ubuntu@focal:~/swift_atomics_test$ swift build && ./.build/debug/SwiftAtomicsTest
Building for debugging...
Build complete! (0.04s)
before atomic
after atomic
ubuntu@focal:~/swift_atomics_test$
```

Also I found that merging the files into the binary (and not having a static library) or merging the AtomicBool and AtomicValue files resolved the issue.

I tried diffing the compiler flags for the static library and a few notable differences I found were:

Bazel:
```
-static
-enable-batch-mode
-enable-bare-slash-regex
```

Swift:
```
-Xllvm
-aarch64-use-tbi
-disable-objc-interop
-empty-abi-descriptor
-enable-anonymous-context-mangled-names
-j2
-swift-version
5
-target
aarch64-unknown-linux-gnu
```

Note that swift build used the swift-frontend rather than invoking swiftc directly.
At this point I'm feeling pretty stumped and I'm hoping one of you might have some ideas. Thanks!

**Comment by keith** [comment]
If you set `alwayslink = True` on all the library targets does it work around the issue?

**Comment by AttilaTheFun** [comment]
@Keith whoa! That seemed to fix the issue:
```
ubuntu@focal:~/swift_atomics_test$ bazelisk run -s --compilation_mode=dbg --sandbox_debug //Sources/SwiftAtomicsTest
INFO: Analyzed target //Sources/SwiftAtomicsTest:SwiftAtomicsTest (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //Sources/SwiftAtomicsTest:SwiftAtomicsTest up-to-date:
  bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest
INFO: Elapsed time: 0.092s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/Sources/SwiftAtomicsTest/SwiftAtomicsTest
before atomic
after atomic
```

**Comment by AttilaTheFun** [comment]
Why do you think that was necessary? Is there a way we could detect this scenario better / give a better error message?

**Comment by AttilaTheFun** [comment]
I'm going to close this one out for now, but it would be nice if there was a better way to detect these issues automatically.

**Comment by keith** [comment]
It'd be worth checking what symbols are there when it works vs are missing when it doesn't. Maybe something could be done in swift to make sure the symbol is loaded
