### ISSUE TITLE
rules_swift is failing with Bazel@Head

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_swift#1063]
Downstream CI : https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3121#0188f04e-1a81-4e0a-855e-fccc45349718
rules_swift CI : https://buildkite.com/bazel/rules-swift-swift/builds/4323#0188f50d-3d92-4f4c-ad0b-b84e7c0ee849

Platform : MacOS

Logs:
```
error: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
int ZEXPORT compress2(dest, destLen, source, sourceLen, level)     

```
Steps: 
```
git clone https://github.com/bazelbuild/rules_swift.git 
git reset ccfe6efee6e9e47a0fffbe796fe98574f963d6ad --hard
export USE_BAZEL_VERSION=7f7017a44ec40a2a6b22f1c52654e81906e50e4c
bazel build --enable_bzlmod //examples/...

```

CC Greenteam @comius

**Comment by keith** [comment]
Are all CI machines on Xcode 14.3? If so we can merge the fix to this https://github.com/bazelbuild/rules_swift/pull/1051

**Comment by keith** [comment]
it looks like no, so  that is kinda of hard to land since there isn't an easy way to conditionalize that setting based on the current Xcode version

**Comment by meteorcloudy** [comment]
We still have a few machines to update /cc @fweikert

**Comment by fweikert** [comment]
There are still ongoing problems with Xcode: https://github.com/bazelbuild/continuous-integration/issues/1431#issuecomment-1586270354

**Comment by sgowroji** [comment]
Closing this issue as the CI shows green now !
