### ISSUE TITLE
Integrating 3rd party framework with Bazel to iOS project

### ISSUE THREAD

**Issue by pressanykeyplease** [bazelbuild/rules_swift#1066]
This issue describes my current difficulties, and I believe will be helpful for other developers leaning Bazel.

There's a [Telegram](https://github.com/TelegramMessenger/Telegram-iOS) repository built with Bazel. My goal is to import 3rd party framework to this project. As an example, I use [PortSIP VoIP SDK](https://www.portsip.com/downloads/sdk/iOSSample.zip).

I've created a `third-party/PortSIP` directory that includes:

* PortSIPVoIPSDK.framework folder from the link above
* BUILD file with the following content:

```
load(
    "@build_bazel_rules_apple//apple:apple.bzl", "apple_dynamic_framework_import",
)

apple_dynamic_framework_import(
    name = "PortSIPVoIPSDK",
    framework_imports = glob(
        ["PortSIPVoIPSDK.framework/**"],
    ),
    visibility = ["//visibility:private"],
)

objc_library(
    name = "PortSIP",
    enable_modules = True,
    module_name = "PortSIP",
    deps = [
        ":PortSIPVoIPSDK",
    ],
    linkopts = ["-lresolv"],
    sdk_frameworks = [
        "AudioToolbox",
        "AVFoundation",
        "CoreGraphics",
        "VideoToolbox",
        "UIKit",
        "CoreMedia",
        "CoreVideo",
        "OpenGLES",
        "CoreGraphics",
        "QuartzCore",
    ],
    weak_sdk_frameworks = [
        "Network",
        "Metal",
        "MetalKit",
        "GLKit",
    ],
    visibility = [
        "//visibility:public",
    ],
)
```

I can successfully generate an Xcode project, but can't build it for device/simulator because of multiple "duplicate symbol" error. Here's an example of the error:

```
duplicate symbol '_SSL_CTX_set_default_passwd_cb' in:
    third-party/PortSIP/PortSIPVoIPSDK.framework/PortSIPVoIPSDK(ssl_lib.o)
    bazel-out/ios-arm64-min11.0-applebin_ios-ios_arm64-dbg-ST-5c7af15d0d89/bin/third-party/boringssl/libssl.a(ssl_file.o)
```

Is there a way to fix this or isolate internal dependencies so they won't conflict with other dependencies in the project?

**Comment by keith** [comment]
It looks like the project already depends on boringssl, and the PortSIPVoIPSDK embeds a copy of boringssl itself. The error is saying that there is a conflict trying to lint 2 copies of boringssl into 1 binary. The ideal solution in this case would be to remove the embedded copy of boringssl from PortSIPVoIPSDK and depend on the one that is already in the build, but depending on if you control the SDK that can be difficult. I think your other best option would be to link PortSIPVoIPSDK as a dynamic framework, thus hiding its copy of boringssl, and including it that way.

**Comment by pressanykeyplease** [comment]
@keith yes you're absolutely right. I followed the same logic and used the **swift_dynamic_framework_rule**, but still got this error. Is there another rule that will fix the issue? Or maybe there's a better way to import dynamic framework?

**Comment by keith** [comment]
If the framework you have isn't a dynamic framework, importing it as one wouldn't work. In that case you'd likely have to wrap your `apple_static_framework_import` in an `ios_framework` rule

**Comment by pressanykeyplease** [comment]
@Keith as far as I can assume it is a dynamic framework. At least Xcode's Mach-O build setting says so, and command `file PortSIPVoIPSDK` gives me the following output:

```
PortSIPVoIPSDK: Mach-O universal binary with 2 architectures: [x86_64:current ar archive] [arm64]
PortSIPVoIPSDK (for architecture x86_64): current ar archive
PortSIPVoIPSDK (for architecture arm64):	current ar archive
```

If I'm wrong, can you please help me to choose the correct rule for that state?

**Comment by keith** [comment]
`current ar archive` means it's a static library

**Comment by pressanykeyplease** [comment]
My bad. I thought Mach-O is a right indicator to tell it's dynamic. Will convert it to dynamic and report - thank you @keith

**Comment by pressanykeyplease** [comment]
@Keith Hi, I've tried to convert the static library to dynamic framework and import it using the following tools in BUILD file:

```
load(
    "@build_bazel_rules_apple//apple:apple.bzl", "apple_dynamic_framework_import",
)

apple_dynamic_framework_import(
    name = "PortSIPVoIPSDK",
    bundle_only = True,
    framework_imports = glob(
        ["PortSIP.framework/**"],
    ),
    visibility = ["//visibility:private"],
)

objc_library(
    alwayslink = 0,
    name = "PortSIP",
    enable_modules = True,
    module_name = "PortSIP",
    deps = [
        ":PortSIPVoIPSDK",
    ],
    sdk_dylibs = [
        "libresolv",
    ],
    sdk_frameworks = [
        "AudioToolbox",
        "AVFoundation",
        "CoreGraphics",
        "VideoToolbox",
        "UIKit",
        "CoreMedia",
        "CoreVideo",
        "OpenGLES",
        "CoreGraphics",
        "QuartzCore",
    ],
    weak_sdk_frameworks = [
        "Network",
        "Metal",
        "MetalKit",
        "GLKit",
    ],
    visibility = [
        "//visibility:public",
    ],
)
```

With `ios_framework` declaration in the app's BUILD file:

```
plist_fragment(
   name = "PortSIPInfoPlist",
   extension = "plist",
   template =
   """
   <key>CFBundleIdentifier</key>
   <string>{telegram_bundle_id}.PortSIPFramework</string>
   <key>CFBundleDevelopmentRegion</key>
   <string>en</string>
   <key>CFBundleName</key>
   <string>PortSIPFramework</string>
   <key>CFBundlePackageType</key>
   <string>FMWK</string>
   """.format(
       telegram_bundle_id = telegram_bundle_id,
   )
)

ios_framework(
   name = "PortSIPFramework",
   bundle_id = "{telegram_bundle_id}.PortSIPFramework".format(
       telegram_bundle_id = telegram_bundle_id,
   ),
   bundle_only = True,
   families = [
       "iphone",
       "ipad",
   ],
   infoplists = [
       ":PortSIPInfoPlist",
       ":BuildNumberInfoPlist",
       ":VersionInfoPlist",
       ":RequiredDeviceCapabilitiesPlist",
   ],
   linkopts = [
    "-ObjC",
    ],
   minimum_os_version = minimum_os_version,
   extension_safe = True,
   ipa_post_processor = strip_framework,
   deps = [
       "//third-party/PortSIP:PortSIP",
   ],
)
```

And including that framework to `frameworks` section of the `ios_application`. I can even integrate that framework in some project's modules using:

```
deps = [
    "//third-party/PortSIP:PortSIP",
]
```

and run `import PortSIP` in the Swift project. However, Xcode gives me this error when I'm trying to build Xcode project with some calls to PortSIP SDK methods:

```
Undefined symbols for architecture arm64:
"_OBJC_CLASS_$ _PortSIPSDK", referenced from:
obic-class-ref in libAccountContext.alAccountContext.swift.o)
Id: symbol(s) not found for architecture arm64
```

I assume it means that the framework wasn't copied to the app. Is there a way to fix that?

**Comment by keith** [comment]
You should remove `bundle_only = True,`

**Comment by pressanykeyplease** [comment]
> You should remove `bundle_only = True,`

Thanks for your reply! Just tried to remove that from:

* `apple_dynamic_framework_import`
* `ios_framework`
* both of them

Unfortunately no luck yet, Xcode project says `No such module` when trying to build. Is there something else I can try?

**Comment by keith** [comment]
can you push a repro?

**Comment by pressanykeyplease** [comment]
> can you push a repro?

Yes sure!

### To reproduce from scratch
1. Clone original [Telegram-iOS](https://github.com/TelegramMessenger/Telegram-iOS) project
2. Integrate the [PortSIP VoIP SDK](https://www.portsip.com/downloads/sdk/iOSSample.zip) from their website
3. Build the full Bazel project using Telegram's Readme

### To reproduce from my current state
1. Clone my [Telegram's fork](https://github.com/pressanykeyplease/Telegram-PortSIP)
2. Look at the last commit to see current progress
4. [Download](https://drive.google.com/file/d/1Aetx4OEyatPUAfEUtHlDKEaajsxez6rB/view?usp=sharing) Dynamic version of PortSIP SDK (self-made), unzip and paste it in `/third-party/PortSIP/`
5. Build the full Bazel project using Telegram's Readme

**Comment by pressanykeyplease** [comment]
@Keith hope that's enough for reproducing. Please let me know if something else is required 👍

**Comment by keith** [comment]
What target are you building for in this case? This framework only has an iOS device slice so if you're building for the simulator that won't work.

**Comment by keith** [comment]
when i try to build i see various duplicate symbol issues:
```
duplicate symbol 'vtable for cricket::Port' in:
    bazel-out/ios-arm64-min11.0-applebin_ios-ios_arm64-fastbuild-ST-2967bd56a867/bin/third-party/webrtc/libwebrtc_lib.a(port_68eb028168ccf76708fd1934df0b9f6a.o)
    third-party/PortSIP/PortSIP.framework/Frameworks/PortSIPVoIPSDK.framework/PortSIPVoIPSDK(port.o)
ld: 3076 duplicate symbols for architecture arm64
```

I think you'll probably have to debug your case some more

**Comment by pressanykeyplease** [comment]
> ```
> duplicate symbol 'vtable for cricket::Port' in:
>     bazel-out/ios-arm64-min11.0-applebin_ios-ios_arm64-fastbuild-ST-2967bd56a867/bin/third-party/webrtc/libwebrtc_lib.a(port_68eb028168ccf76708fd1934df0b9f6a.o)
>     third-party/PortSIP/PortSIP.framework/Frameworks/PortSIPVoIPSDK.framework/PortSIPVoIPSDK(port.o)
> ld: 3076 duplicate symbols for architecture arm64
> ```

Hi @Keith thanks for your response! That's actually the same error described at the first message of this thread. So I followed your instructions and packed PortSIPVoIPSDK into dynamic framework (I've attached it [here](https://drive.google.com/file/d/1Aetx4OEyatPUAfEUtHlDKEaajsxez6rB/view?usp=sharing)). Now `duplicate symbols` error is gone, but Xcode gives me this error when I'm trying to build the project with some calls to PortSIP SDK methods:

```
Undefined symbols for architecture arm64:
"_OBJC_CLASS_$ _PortSIPSDK", referenced from:
obic-class-ref in libAccountContext.alAccountContext.swift.o)
Id: symbol(s) not found for architecture arm64
```

Tried different combinations of rules but no luck yet. That's the biggest problem I had! Will appreciate any help or reference to the same challenge 🙏

**Comment by keith** [comment]
did you remove bundle_only? that wasn't removed on your branch when i cloned. you also do need either `-ObjC` or `-all_load` in the linkopts of that ios_framework

**Comment by pressanykeyplease** [comment]
@Keith just followed your instructions and got the duplicate symbols back. I thought it will easier to solve this:

```
Undefined symbols for architecture arm64:
"_OBJC_CLASS_$ _PortSIPSDK", referenced from...
```

than `duplicate symbols` error. However, `duplicate symbols` is strange for me. Aren't these symbols hidden by dynamic framework? What is the proper way to declare that kind of dependency? I can't find similar examples

**Comment by keith** [comment]
Ok so I see some of the confusion, this glob:

```
    framework_imports = glob(
        ["PortSIP.framework/**"],
```

Currently pulls in both the PortSIP binary and this binary: `PortSIP.framework/Frameworks/PortSIPVoIPSDK.framework/PortSIPVoIPSDK` where the former is dynamic and the latter is static, so those need to be broken up. Just using this BUILD file works:

```bzl
load(
    "@build_bazel_rules_apple//apple:apple.bzl",
    "apple_dynamic_framework_import",
)

apple_dynamic_framework_import(
    name = "PortSIP",
    framework_imports = glob(
        ["PortSIP.framework/**"],
        exclude = [
            "PortSIP.framework/Frameworks/**",
        ],
    ),
    visibility = ["//visibility:public"],
)
```

But if you _need_ the behavior from the `PortSIPVoIPSDK`, the duplicate symbol problem is because `PortSIP` is a dependency of `AccountContext` and somewhere is missing a `frameworks = [":PortSIPFramework"]` to make sure `PortSIPVoIPSDK` isn't statically linked into `TelegramUIFramework` (if you look at which link command fails that one was the issue for me). I tried adding `PortSIPFramework` to `TelegramUIFramework`'s `frameworks` but that wasn't enough. Removing `PortSIP` as a dependency from `AccountContext` worked around the issue though (it looks like right now the import is used but the dependency isn't, but maybe that would change with your code?). I think that's a good place to start and you should be able to figure out where that missing `frameworks` is. This was the BUILD file I got working in that case:

```bzl
load(
    "@build_bazel_rules_apple//apple:apple.bzl",
    "apple_static_framework_import",
)

apple_static_framework_import(
    name = "PortSIPVoIPSDK",
    framework_imports = glob(
        ["PortSip.framework/Frameworks/PortSIPVoIPSDK.framework/**"],
    ),
    sdk_dylibs = [
        "resolv",
    ],
    sdk_frameworks = [
        "AudioToolbox",
        "AVFoundation",
        "CoreGraphics",
        "VideoToolbox",
        "UIKit",
        "CoreMedia",
        "CoreVideo",
        "OpenGLES",
        "CoreGraphics",
        "QuartzCore",
    ],
    weak_sdk_frameworks = [
        "Network",
        "Metal",
        "MetalKit",
        "GLKit",
    ],
)

load(
    "@build_bazel_rules_apple//apple:apple.bzl",
    "apple_dynamic_framework_import",
)

apple_dynamic_framework_import(
    name = "PortSIP",
    framework_imports = glob(
        ["PortSIP.framework/**"],
        exclude = [
            "PortSIP.framework/Frameworks/**",
        ],
    ),
    visibility = ["//visibility:public"],
    deps = [":PortSIPVoIPSDK"],
)
```

**Comment by keith** [comment]
it seems like since you can safely remove that dependency from here https://github.com/pressanykeyplease/Telegram-PortSIP/blob/899878d0689072751d6dd13e59b37ef0fa178c0f/submodules/AccountContext/BUILD#L29 since it's unused, you should be good to go here

**Comment by pressanykeyplease** [comment]
> it seems like since you can safely remove that dependency from here https://github.com/pressanykeyplease/Telegram-PortSIP/blob/899878d0689072751d6dd13e59b37ef0fa178c0f/submodules/AccountContext/BUILD#L29 since it's unused, you should be good to go here

But in that case it cannot be used within that submodule?

**Comment by keith** [comment]
Should be fine as long as you add it to the correct frameworks
