### ISSUE TITLE
rules_swift is failing with Bazel@HEAD in CI

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_swift#1093]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3256#018a202d-c126-4377-9286-aa36c305ed76

Main pipeline https://buildkite.com/bazel/rules-swift-swift/builds/4473#018a2090-44ee-4d64-bc5b-7faceb961171

Platform : Linux

Log : 
```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/e0fba04d7d9e5bdfaeacf1eecab3e828/external/build_bazel_rules_swift_local_config/BUILD:9:16: While resolving toolchains for target @build_bazel_rules_swift_local_config//:toolchain: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type.
To debug, rerun with --toolchain_resolution_debug='@bazel_tools//tools/cpp:toolchain_type'
If platforms or toolchains are a new concept for you, we'd encourage reading https://bazel.build/concepts/platforms-intro.
(02:17:07) ERROR: Analysis of target '//examples/apple/objc_interop:main' failed; build aborted: Analysis failed

```

Steps : 
```
git clone -v https://github.com/bazelbuild/rules_swift.git

git reset 5e58cfc00d3fc3fe0beb1ff68b30d5e08c5dc07c --hard
export USE_BAZEL_VERSION=6a19449233d6e51d8a862545726a60a611943068

shell_commands:
      - "echo --- Downloading and extracting Swift $SWIFT_VERSION to $SWIFT_HOME"
      - "mkdir $SWIFT_HOME"
      - "curl https://download.swift.org/swift-${SWIFT_VERSION}-release/ubuntu2004/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-ubuntu20.04.tar.gz | tar xvz --strip-components=1 -C $SWIFT_HOME"
   
 bazel build //examples/...
    
```

CC Greenteam @SalmaSamy

**Comment by keith** [comment]
Did you bisect this one? I'm surprised that it only broken on linux w/o any changes on our side

**Comment by keith** [comment]
broken by https://github.com/bazelbuild/bazel/commit/03b8616b4fdd088c5ad9a9959c2a365e87728d52

**Comment by keith** [comment]
it's because of these objc_library targets even though they are marked as incompatible on linux https://github.com/bazelbuild/rules_swift/blob/270c989b564a64a87891466a92b2c01d6b83698d/examples/apple/objc_interop/BUILD#L13-L18

**Comment by keith** [comment]
likely related: https://github.com/bazelbuild/bazel/issues/16662

**Comment by keith** [comment]
and maybe https://github.com/bazelbuild/bazel/issues/16099

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_swift/pull/1094

**Comment by sgowroji** [comment]
Thanks @keith!
