### ISSUE TITLE
Error in fail: Compiling objc_library targets requires the Apple CC toolchain

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_swift#1115]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3319#018ab078-1251-4412-a17f-cc5e782ea20e

Platform : rules_swift (Current LTS using bzlmod on :darwin: (OpenJDK 11, Xcode))

Logs:
```
ERROR: /Users/buildkite/builds/bk-imacpro-18/bazel-downstream-projects/rules_swift/examples/apple/objc_interop/BUILD:13:13: in objc_library rule //examples/apple/objc_interop:PrintStream:
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/objc/objc_library.bzl", line 61, column 52, in _objc_library_impl
	File "/virtual_builtins_bzl/common/objc/semantics.bzl", line 54, column 13, in _check_toolchain_supports_objc_compile
Error in fail: Compiling objc_library targets requires the Apple CC toolchain which can be found here: https://github.com/bazelbuild/apple_support#toolchain-setup
(05:10:10) ERROR: /Users/buildkite/builds/bk-imacpro-18/bazel-downstream-projects/rules_swift/examples/apple/objc_interop/BUILD:13:13: Analysis of target '//examples/apple/objc_interop:PrintStream' failed
(05:10:10) ERROR: Analysis of target '//examples/apple/objc_interop:PrintStream' failed; build aborted
(05:10:10) ERROR: Build did NOT complete successfully
```

Steps:
```
git clone https://github.com/bazelbuild/rules_swift.git 
git reset 8c0904124f3b7fbeb08d7863b8b5949cbe359252 --hard
export USE_BAZEL_VERSION=81b4b91bc98acc404690cd833cd6a1a592f3ee17
bazel build --enable_bzlmod --platform_mappings=platform_mappings_bzlmod //examples/...
```
Culprit Found: [1be55d8add84c2d04c3353b7e481a7866a92eac7](https://github.com/bazelbuild/bazel/commit/1be55d8add84c2d04c3353b7e481a7866a92eac7)

Cc Greenteam @comius

**Comment by brentleyjones** [comment]
This requires a fix in Bazel, with a new rules_cc release. @meteorcloudy is working on that now.

**Comment by brentleyjones** [comment]
> But this could be brittle

You're telling me! Seems like a Bazel change is needed for that.

**Comment by meteorcloudy** [comment]
But I have no idea what else we could do from Bazel side, toolchain registrations has to have an order, and it is currently a BFS order from the root module.

**Comment by katre** [comment]
The problem is that there are multiple matching cc toolchains, at least one from `apple_support` and another from `rules_cc`, and the wrong one is being used? Do we know which toolchains those are?

The best idea we've come up with so far would be to add a `priority` parameter to the existing `register_toolchains` function. However, it's hard to figure out how to define this so that `rules_cc` uses a lower priority than `apple_support`.

Instead of this, can the problematic `cc_toolchain` entries be removed from `rules_cc`?

**Comment by meteorcloudy** [comment]
Yeah, sounds like we should remove the toolchain registration in rules_cc all together.

**Comment by comius** [comment]
Why not removing it from bazel_tools instead?

**Comment by comius** [comment]
I think that rules_cc and rules_java should do the toolchain registration themselves, and it shouldn't happen in @bazel_tools.

That is because then the rules_java, rules_cc repos can be updated independently of Bazel.

**Comment by meteorcloudy** [comment]
I agree that should be the plan in the long term, but in short term maybe removing the toolchain registration from rules_cc is better for users?
See https://github.com/bazelbuild/rules_cc/pull/199#issuecomment-1729143915

**Comment by sgowroji** [comment]
Above failures are not shown in the latest CI. Hence we are closing this issue now.
