### ISSUE TITLE
It is not possible to use `@testable` when `compilation_mode=opt`

### ISSUE THREAD

**Issue by luispadron** [bazelbuild/rules_swift#1134]
I have a CI job using Swift Package Manager which runs `swift test -c debug` and `swift test -c release`. 

This works just fine with SPM, but doing the same in Bazel with `bazel test //... --compilation_mode=opt` fails in unit tests targets which use `@testable`.

I receive an error like:

```sh
ERROR: /Users/lpadron/Development/swift-command-line-tools/Tests/CommandLineKitTests/BUILD.bazel:3:11: Compiling Swift module //Tests/CommandLineKitTests:CommandLineKitTests failed: (Exit 1): worker failed: error executing command (from target //Tests/CommandLineKitTests:CommandLineKitTests)
  (cd /private/var/tmp/_bazel_lpadron/ec6e04f7d6adcccc01cbe07a20e90f4a/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=14.0 \
    SWIFT_AVOID_WARNING_USING_OLD_DRIVER=1 \
    XCODE_VERSION_OVERRIDE=15.0.0.15A240d \
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/rules_swift~1.13.0/tools/worker/worker swiftc @bazel-out/darwin_arm64-opt/bin/Tests/CommandLineKitTests/CommandLineKitTests.swiftmodule-0.params)
# Configuration: 2d4ade0d5d260ee021b26267fcc446583bcdfbd8fbd263071a0334f83b1eed99
# Execution platform: @local_config_platform//:host
Tests/CommandLineKitTests/CommandLineKitTests.swift:4:18: error: module 'CommandLineKit' was not compiled for testing
@testable import CommandLineKit
```

**Comment by keith** [comment]
You can pass `--features=swift.enable_testing`, or set that in `features` on the relevant targets. I don't think we should make this the default to avoid accidentally shipping testable uses in prod

**Comment by luispadron** [comment]
This seems expected based on the doc for this flag `swift.enable_testing`:

> This feature will be enabled by default for
> # dbg/fastbuild builds and disabled by default for opt builds.

**Comment by luispadron** [comment]
Thats fair @keith, should've spent like 1 more minute searching haha.
