### ISSUE TITLE
Duplicate symbol  error when migrating to bzlmod

### ISSUE THREAD

**Issue by tinder-kaijing** [bazelbuild/rules_swift#1153]
We are migrating our IOS repo to use bzlmod. and see below duplicate symbol error. Has anyone seen the same error before? Any idea? The rules_swift(1.13.0), rules_apple(3.1.1) and rules_xcodeproj(1.13.0) are the same. 

we have a `build --proto_compiler=@build_bazel_rules_swift//tools/protoc_wrapper:protoc` set in .bazelrc.

Here is the error log:

```
duplicate symbol '_$s13SwiftProtobuf07Google_B13_FieldOptionsV5CTypeO8allCasesSayAEGvgZ' in:
    bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-fastbuild-ST-3f2dc29f722a/bin/external/rules_swift~1.13.0~non_module_deps~com_github_apple_swift_protobuf/libSwiftProtobuf.a[77](descriptor.pb.swift.o)
    bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-fastbuild-ST-3f2dc29f722a/bin/external/_main~non_module_dependencies~com_github_apple_swift_protobuf/libSwiftProtobuf.a[77](descriptor.pb.swift.o)
duplicate symbol '_$s13SwiftProtobuf01_B3MapVMn' in:
    bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-fastbuild-ST-3f2dc29f722a/bin/external/rules_swift~1.13.0~non_module_deps~com_github_apple_swift_protobuf/libSwiftProtobuf.a[55](ProtobufMap.swift.o)
    bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-fastbuild-ST-3f2dc29f722a/bin/external/_main~non_module_dependencies~com_github_apple_swift_protobuf/libSwiftProtobuf.a[55](ProtobufMap.swift.o)
ld: 5172 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
```

**Comment by mattrobmattrob** [comment]
Can you provide a simple `.proto` and targets that replicate this failure? It'll help with debugging!

**Comment by brentleyjones** [comment]
Looks like rules_swift and the root `MODULE.bazel` both have module extensions that bring in `com_github_apple_swift_protobuf`. I would remove it from your root module.

**Comment by tinder-kaijing** [comment]
> Looks like rules_swift and the root `MODULE.bazel` both have module extensions that bring in `com_github_apple_swift_protobuf`. I would remove it from your root module, and instead `use_repo` rules_swift's version.

@brentleyjones Thanks very much. If to remove  `com_github_apple_swift_protobuf` from root `MODULE.bazel`. we have some modules which depend on
deps = [
      ..
     "@com_github_apple_swift_protobuf//:SwiftProtobuf",
]
 How to use rules_swift's  SwiftProtobuf to replace it? I try below, not work. shows not BUILD file error in `@build_bazel_rules_swift//third_party/com_github_apple_swift_protobuf`

deps = [
      ..
     "@build_bazel_rules_swift//third_party/com_github_apple_swift_protobuf:SwiftProtobuf",
]

**Comment by tinder-kaijing** [comment]
@brentleyjones  You are correct, After removing com_github_apple_swift_protobuf from own's non_module_dependencies and directly use it from build_bazel_rules_swift, then this issue gets fixed.

rules_swift_deps = use_extension(
    "@build_bazel_rules_swift//swift:extensions.bzl",
    "non_module_deps",
)
use_repo(
    rules_swift_deps,
    "com_github_apple_swift_protobuf",
)
