### ISSUE TITLE
Add example of Swift <--> C++ interop

### ISSUE THREAD

**Issue by jiawen** [bazelbuild/rules_swift#1198]
In the last year, Swift has gradually gained the [ability to interop with C++](https://www.swift.org/documentation/cxx-interop/). `rules_swift` should add a minimal example on how that would work. It would provide at baseline a means by which we can easily reproduce issues (module naming, static and dynamic linking, ODR violations, etc) as they are discovered.

**Comment by gkoreman** [comment]
Yes please!

I just tried this out and was pleasantly surprised at how easy it was. Here are some quick notes based on my experience in case anyone else sees this before the examples come out.

BUILD
```
swift_library(
    name = "mySwiftLib",
    srcs = [ "lib.swift" ], #note - if you make this main.swift then it will have an extra _main symbol which conficts with your app
    generates_header = True,
    copts = ["-cxx-interoperability-mode=default"], #needed to export c++ bindings
)

cc_binary(
...
    deps = [":mySwiftLib"]
)
```

SWIFT lib.swift
```
public func printWelcomeMessage(_ name: String) {
  print("Welcome \(name)")
}
```

C++
```
#include "full/path/to/module/mySwiftLib-Swift.h"

int main(int, char**)
{
    // Namespace appears to be the full path to the module
    full_path_to_module::printWelcomeMessage("friend");
    return 0;
}
```

**Comment by davidzchen** [comment]
It would be great to have an example of the other way around: calling C++ code from Swift. This will make it easier for developers to utilize C++ libraries in Swift code.

**Comment by jiawen** [comment]
@brentleyjones I just whipped up a short example of calling Swift from C++ (the first part of the [Mountain Peak example](https://www.swift.org/documentation/cxx-interop/#creating-a-swift-structure-in-c)). Should I put up a PR to include it in the examples?
