### ISSUE TITLE
README.md has broken link to docs

### ISSUE THREAD

**Issue by romoore** [bazelbuild/rules_swift#143]
The link for attributes docs for the rules is broken. It's currently `https://github.com/bazelbuild/rules_swift/tree/master/doc/index.md`, I'm not sure what it should be.

**Comment by keith** [comment]
It was moved to README.md https://github.com/bazelbuild/rules_swift/commit/c5d378f92b6535f8b72c3488b12a59c4cff18697 I've submitted https://github.com/bazelbuild/rules_swift/pull/144 to change it to that directory which will show the readme
