### ISSUE TITLE
mixed_language_library data attribute ignored ?

### ISSUE THREAD

**Issue by vakhidbetrakhmadov** [bazelbuild/rules_swift#1449]
Hi,

I have the following setup: `ios_application` -> `mixed_language_library` -> `...`.

When i add a resource to `data` attribute of  the `mixed_language_library` i expect that resource to be included at the top level of the produced app bundle, currently that doesn't happen. 

Previously i had the following setup `ios_application` -> `apple_framework` -> `...` and it worked as expected.

**Comment by vakhidbetrakhmadov** [comment]
Just in case, my current workaround is to use resources attribute of the ios_application

**Comment by brentleyjones** [comment]
Actually a rules_apple bug. I'll reopen the other one.
