### ISSUE TITLE
swift_library cannot see c headers

### ISSUE THREAD

**Issue by matthewcheok** [bazelbuild/rules_swift#161]
I'm trying to build the [SwiftGRPC library](https://github.com/grpc/grpc-swift) but I'm running into the following problem where the build fails because bazel cannot find the identifiers in the c header file. Here's my configs below:

WORKSPACE
```
http_archive(
    name = "SwiftProtobuf",
    url = "https://github.com/apple/swift-protobuf/archive/1.4.0.zip",
    strip_prefix = "swift-protobuf-1.4.0",
    build_file = "SwiftProtobuf/BUILD.bazel")

http_archive(
    name = "SwiftGRPC",
    url = "https://github.com/grpc/grpc-swift/archive/0.8.0.zip",
    strip_prefix = "grpc-swift-0.8.0",
    build_file = "SwiftGRPC/BUILD.bazel")
```

SwiftProtobuf/BUILD.bazel
```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
  name = "SwiftProtobuf",
  module_name = "SwiftProtobuf",
  srcs = glob(["Sources/SwiftProtobuf/**/*.swift"]),
  visibility = ["//visibility:public"],
)
```

SwiftGRPC/BUILD.bazel
```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_c_module")

cc_library(
  name = "CgRPCLib",
  srcs = glob([
    "Sources/CgRPC/**/*.[ch]",
    ]),
  hdrs = ["Sources/CgRPC/shim/cgrpc.h"],
)

swift_c_module(
  name = "CgRPC",
  deps = [":CgRPCLib"],
  module_map = "Sources/CgRPC/include/module.modulemap",
)

swift_library(
  name = "SwiftGRPC",
  deps = [
    "@SwiftProtobuf//:SwiftProtobuf",
    ":CgRPC",
  ],
  srcs = glob(["Sources/SwiftGRPC/**/*.swift"]),
)
```

**Comment by allevato** [comment]
It's difficult to say without seeing the actual error message you're getting, but we plan to add gRPC-Swift support (and a `swift_grpc_library` rule to generate the service/client code) very soon so you won't need to pull the dependencies in manually or worry about setting up those targets.

**Comment by matthewcheok** [comment]
Here's a fraction of the errors I'm seeing:
```
external/SwiftGRPC/Sources/SwiftGRPC/Core/gRPC.swift:25:5: error: use of unresolved identifier 'grpc_init'
    grpc_init()
    ^~~~~~~~~
external/SwiftGRPC/Sources/SwiftGRPC/Core/gRPC.swift:30:5: error: use of unresolved identifier 'grpc_shutdown'
    grpc_shutdown()
    ^~~~~~~~~~~~~
external/SwiftGRPC/Sources/SwiftGRPC/Core/gRPC.swift:36:28: error: use of unresolved identifier 'grpc_version_string'
    return String(cString: grpc_version_string(), encoding: .utf8)!
                           ^~~~~~~~~~~~~~~~~~~
external/SwiftGRPC/Sources/SwiftGRPC/Core/gRPC.swift:41:28: error: use of unresolved identifier 'grpc_g_stands_for'
    return String(cString: grpc_g_stands_for(), encoding: .utf8)!
```

**Comment by matthewcheok** [comment]
To clarify - I'm trying to use this to link the runtime into my application.

**Comment by keith** [comment]
The problem in this case isn't an issue with rules_swift, it's an issue with how SwiftGRPC is setup to build. The problem is SwiftGRPC builds differently for dependency managers like CocoaPods (the default) vs SwiftPM (which is more like how you're trying to configure it for bazel).

The difference is that SwiftGRPC only imports CgRPC if `-DSWIFT_PACKAGE` is passed to the compiler https://github.com/grpc/grpc-swift/blob/c401b44ea81b246b8e7fea191ea1ee11a834ee60/Sources/SwiftGRPC/Core/Operation.swift#L16-L18

To do this, change your build file for SwiftGRPC to pass this flag:

```python
# omitted the CgRPC config

swift_library(
    name = "SwiftGRPC",
    srcs = glob(["Sources/SwiftGRPC/**/*.swift"]),
    visibility = ["//visibility:public"],
    deps = [
        ":CgRPC",
        "@SwiftProtobuf",
    ],
    copts = ["-DSWIFT_PACKAGE"],
)
```

Here's a full sample project that shows this working [grpc.zip](https://github.com/bazelbuild/rules_swift/files/2979727/grpc.zip)

**Comment by matthewcheok** [comment]
Thanks a bunch!  This works.
