### ISSUE TITLE
Runtime error on iOS 12.2

### ISSUE THREAD

**Issue by matthewcheok** [bazelbuild/rules_swift#177]
I'm getting the following error in the console after updating my device to 12.2 (or using the 12.2 simulator.) Do I need to change my build files? It was working fine on 12.1

```
This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.
2019-04-09 09:25:11.677514-0700[61813:6155466] This copy of libswiftCore.dylib requires an OS version prior to 12.2.0.
```

**Comment by keith** [comment]
Can you try with the bazel 0.25.0rc1? It contains this fix https://github.com/bazelbuild/bazel/pull/7830

**Comment by matthewcheok** [comment]
How can I install this verison?

**Comment by keith** [comment]
You can download it from this page https://releases.bazel.build/0.25.0/rc1/index.html or use [bazelisk](https://github.com/philwo/bazelisk) with this environment `USE_BAZEL_VERSION=0.25.0rc1`

**Comment by matthewcheok** [comment]
this works!
