### ISSUE TITLE
Using swift_c_module in a Swift framework

### ISSUE THREAD

**Issue by chronal-xnor** [bazelbuild/rules_swift#190]
First off, I'm aware there's a [roadmap item](https://github.com/bazelbuild/rules_apple/issues/355) for Framework support in rules_apple and that right now it's not a supported use case for these tools. However, I'm striving to use the tools that are available to hack one together regardless.

Creating a pure Swift framework seems to be "some-assembly-required" right now, but is possible. I can take a `.swiftmodule` and `.swiftdoc` from the outputs of a `swift_library` target, put them in the `Modules/` folder of a framework, and import it successfully into an independent XCode project.

However, if that `swift_library` depends on a `swift_c_module`, things get tricky. If you stay inside Bazel, things are nice and lovely because the `'-fmodule-map-file=blah'` linker argument gets passed along through the dependency chain, presumably via the SwiftClangModuleInfo provider, and your `import MyCLibrary` statements just work. However, if you try to use the above strategy to pack up a framework by hand, it'll fail to import in user projects with the error:

    UserApplication.swift:10:8: error: missing required module 'MyCLibrary'
    import MySwiftLibrary

Some inspection of the `.swiftmodule` using `llvm-bcanalyzer --dump` reveals (part of) the problem:

    <INPUT_BLOCK NumWords=52 BlockCodeSize=4>
      <SEARCH_PATH abbrevid=9 op0=1 op1=0/> blob data = '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks'
      <IMPORTED_MODULE abbrevid=4 op0=0 op1=0/> blob data = 'Foundation'
      <IMPORTED_MODULE abbrevid=4 op0=0 op1=0/> blob data = 'Swift'
      <IMPORTED_MODULE abbrevid=4 op0=0 op1=0/> blob data = 'SwiftOnoneSupport'
      <IMPORTED_MODULE abbrevid=4 op0=0 op1=0/> blob data = 'MyCLibrary'
    </INPUT_BLOCK>

Namely, the Swift module declares an import dependency on `MyCLibrary`, but there's no `SEARCH_PATH` that will find the module map.

I've tried everything I can think of to declare the existence of MyCLibrary through a `module.map` or `module.modulemap` file in the resulting framework but nothing clues the "end-user" XCode project in to look for the module in the same framework.

It feels like there should be a way to incorporate the C-header/module declaration stuff in the `module.map` into the `.swiftmodule` the same way the symbols from the depended `cc_library` target end up incorporated into the .a, but I haven't seen anything that indicates this is possible inside or outside of Bazel.

Is there anything I can do to avoid infecting "end-user" projects with additional build settings that make my framework harder to use and expose implementation details? Or am I just doomed to make my users add an extra import path in their build settings to get this Swift/C interop detail?

**Comment by chronal-xnor** [comment]
Here's another angle of the problem, maybe it will help make the issue more concrete:

I can solve this problem when building swift bindings in an XCode project by:
1. Add a header and dylib for `MyCLibrary` to the project and the Headers/Search paths sections of the project settings
2. Create a `module.modulemap` file for the project and put contents like the following:
```
framework module MySwiftLibrary {
    umbrella header "MySwiftLibrary.h"
    export *
    module * {export *}
    header "MyCLibrary.h"
}
```
3. Set MODULEMAP_FILE in the XCode project settings to the path to `module.modulemap` file defined in 2
4. Use symbols defined in "MyCLibrary.h" in swift files without an import

This is different from the solution I was trying to get to work above because it includes the C symbols and swift symbols in the same module, which also avoids users of MySwiftLibrary seeing an extra, implementation-detail module when adding MySwiftLibrary.framework to their project.

However, `rules_swift` doesn't seem to support this approach, because I can't create `swift_library` targets that occupy the same module as C symbols. That is, there's no way for me to make that `module.modulemap` declaration in the language of `rules_swift`. If I create a `swift_c_module` with my C symbols and its own `module.map`, and add it as a dependency of `swift_library(name = "MySwiftLibrary", ...)`, the swift compilation isn't aware of the C symbols being present in the same module.

So I guess the concrete feature request for this issue is: add the equivalent of XCode's `MODULEMAP_FILE` setting to allow users to declare what's in their swift modules.

**Comment by chronal-xnor** [comment]
This is the hack mentioned in https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/api.bzl#L765

**Comment by allevato** [comment]
Frameworks are a bit of a special case in Apple land, especially w.r.t. how they interact with modules. Frameworks really only support a single module due to the search/load logic used by the compiler (they assume that the `.framework` name and the `.swiftmodule` name match, and won't look for modules of different names inside that bundle. So the solution in your earlier comment of using `-import-underlying-module` is really the only way to make that work.

Even if we exclude Objective-C and Apple platforms from the equation, there _are_ situations where it's handy to have C code in the same module as Swift code (the Swift core libraries do this in a handful of places), but it's also rare enough that it hasn't been a high priority to figure out how to handle it generally when the hack above gets most of the way there, and when rules_apple is planning on handling the case there (where it is more common, especially due to the framework issue).

Since rules_apple is going to handle the common case, I'm going to close out this issue—I'll suggest following the issue over there to get a solution that handles your use case.
