### ISSUE TITLE
How to use UIKit with swift_library

### ISSUE THREAD

**Issue by LeeWong** [bazelbuild/rules_swift#240]
I tried to build a library that has UIKit import with swift_library but build fails with the error message: error: no such module 'UIKit' 

`swift_library(
    name = "Kingfisher",
    module_name = "Kingfisher",
    srcs = glob([
        "Sources/**/*.swift"
    ],
    exclude= [
            "Sources/Extensions/NSButton+Kingfisher.swift",
            "Sources/Extensions/WKInterfaceImage+Kingfisher.swift"
        ]
    ),
    visibility = ["//visibility:public"],
)
`
I did not see any sdk_framework option that is similar to objc_library.

**Comment by thii** [comment]
You need to pass the `--apple_platform_type=ios` to your build command. The default `apple_platform_type` value has been changed from `ios` to `macos` since Bazel 0.23.0.

**Comment by LeeWong** [comment]
Thank you so much. @thii Your suggestion fixed the issue.

**Comment by bigbangvn** [comment]
Already pass `--apple_platform_type=ios` (in .bazelrc), but still got that problem

**Comment by keith** [comment]
FWIW you generally shouldn't have to pass that flag at all, just build a ios_application or ios_unit_test target directly instead of building the swift_library target

**Comment by joprice** [comment]
Is there a way to filter only things that are meant to be exposed as buildable leaf nodes? Maybe by querying by platform, or marking something's visibility in such a way that that it isn't picked up by `...`? Otherwise, you lose the convenience to test that everything builds or tests run in a package with a wildcard. 

A workaround is to exclude everything that isn't independently buildable:: `bazel build -- ... -//lib_ios`. Can such an exclusion be managed in bazelrc, or do you recommend a custom build script for e.g. validation in ci?

**Comment by keith** [comment]
I would either recommend marking the library targets `manual`, which would exclude them from any `...`, or building a list of queries with a `bazel query` where you exclude the ones like that you don't want. Alternatively you could mark the targets you _do_ want with a custom tag `buildme` and then use [`--build_tag_filters`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--build_tag_filters) to build only those

**Comment by ouceduxzk** [comment]
same questions here, problem not solved

**Comment by keith** [comment]
As mentioned above instead of building the library directly build a platform specific target

**Comment by sanju-naik** [comment]
But I remember this functionality [directly building swift_library] used to work earlier, It started throwing this error after upgrading to Bazel 6.0. Any other extra flags we need to pass? 

This is super handy when I want to just test if that particular swift_library is building or not [when it has no test target]

**Comment by brentleyjones** [comment]
If you want to make sure the library builds, but for iOS, you should use [ios_build_test](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_build_test). It applies the same transition that something like ios_application applies, so you even get cache hits.

Building library targets directly is sort of an anti-pattern in the world of platforms and transitions.

**Comment by ShukantPal** [comment]
Does the following work?

```
# MODULE.bzl
bazel_dep(name = "apple_support", version = "1.17.1", repo_name = "build_bazel_apple_support")
```

```
# BUILD
load("@build_bazel_apple_support//configs:platforms.bzl", "APPLE_PLATFORMS_CONSTRAINTS")

platform(
    name = "ios",
    constraint_values = APPLE_PLATFORMS_CONSTRAINTS["ios_arm64"],
)
```

Then run your build with `bazel build --platforms=//:ios`.

**Comment by ShukantPal** [comment]
I also don't see any way to specify Swift source files in [ios_application](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application). I'm not sure how you can achieve this without `swift_library` targets :thinking:
