### ISSUE TITLE
Build times and swiftc parallelism

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/rules_swift#258]
I posted on bazel-discuss, but also wanted to create a tracking issue for this.

> For local dev builds on our project, Xcode's build is by default faster than Bazel's.

Bazel's build can be made to be close to on par with Xcode by manually specifying `copts = ["-j8"]` for bottleneck targets and targets that come at the tail of the build. These are points in the build where Bazel isn't able to fully use the cpu, _but_, `swiftc` could be using the extra cores to compile those targets faster. For example one target went from ~30s to ~12s.

The Bazel-discuss post is here: https://groups.google.com/forum/?nomobile=true#!topic/bazel-discuss/_oHaU50P5Rg

**Comment by keith** [comment]
Closing for https://github.com/bazelbuild/bazel/issues/10443
