### ISSUE TITLE
Add .clang-format settings file

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/rules_swift#305]
I ran `clang-format` on the changes I made in #304, but it resulted in a few changes that did not match the existing formatting/style of the rest of the code. For example the indentation of `public:` and `private:`.

Adding a `.clang-format` file would solve this.

**Comment by allevato** [comment]
A `.clang-format` that's just `BasedOnStyle: Google` _should_ be sufficient here, as long as public clang-format does the same thing as ours internally.
