### ISSUE TITLE
download rules_swift.0.9.0.tar.gz failed,  there is no valid certification path

### ISSUE THREAD

**Issue by liakopyangsir** [bazelbuild/rules_swift#309]
error loading package '': Encountered error while reading extension file 'swift/repositories.bzl': no such package '@build_bazel_rules_swift//swift': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_swift/releases/download/0.9.0/rules_swift.0.9.0.tar.gz] to /home/tony/.cache/bazel/_bazel_root/fd5143b235311b392995358a7cf86512/external/build_bazel_rules_swift/rules_swift.0.9.0.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by thomasvl** [comment]
Does this repeat?  Is there a reason you are using the 0.9.0 release, it is pretty old.
