### ISSUE TITLE
swift_library doesn't expand $(GENDIR)

### ISSUE THREAD

**Issue by segiddins** [bazelbuild/rules_swift#314]
I was updating one of my macros to get parity with `objc_library`, and discovered that `$(GENDIR)` is silently not expanded in `swift_library`'s `copt`s, whereas `objc_library` expands it

**Comment by michaeleisel** [comment]
+1 for this

**Comment by thii** [comment]
Anyone who has a use-case for this, please feel free to send a PR with a fix. This can be done with https://docs.bazel.build/versions/4.0.0/skylark/lib/ctx.html#expand_make_variables.
