### ISSUE TITLE
Allow swiftinterface files to be used for intermodule dependency resolution

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#316]
(this issue is meant to continue this conversation) https://github.com/bazelbuild/rules_swift/pull/315#issuecomment-535100093

Now that the first knowledge about the new swiftinterface file has been added to rules_swift https://github.com/bazelbuild/rules_swift/pull/315 I think we should consider going ahead and adding support for swiftinterface files as the connections between swift_library dependencies.

The general goal of this is to solve this issue:

If you have modules A -> B -> C -> D, in the swiftmodule world D's swiftmodule files are inputs to C, C's to B, etc. This means when something you change affects D's swiftmodule file, it causes a rebuild of C. The problem here is that swiftmodule files encode almost everything about a module, and therefore many different types of changes cause them to be updated, even if they won't actually affect dependent modules.

On the other hand the new swiftinterface files only contain the public interface of the module (and some other things like inlinable functions, but that difference doesn't matter too much for this case). If we change dependency resolution to make C depend on D's swiftinterface instead of its swiftmodule, only changes to its _public_ API would cause a rebuild of C, which could greatly reduce the number of actions that need to be run unnecessarily.

**Comment by keith** [comment]
> The private declarations are present in the swiftmodule for the purposes of debugging and diagnostics. Some things, like private stored properties, also have effects on ABI. If you get rid of all that information in your self-contained build from source, you're going to severely degrade your debugging experience, change the semantics of your code, and a number of other things are unlikely to not work the way you expect.

I'm not saying we wouldn't build them anymore, just that they wouldn't be inputs of the swift_library targets that depend on them so they wouldn't require rebuilds. And actually to use `@testable` test `swift_library` targets still have to depend directly on the swiftmodule files (I was thinking this might be do-able by checking `testonly == True`)

**Comment by allevato** [comment]
Folks don't tend to use `testonly` consistently and I'm not crazy about using that attribute as the trigger for `-enable-testing`, let alone module propagation behavior.

Aside from that, even if you generate the original swiftmodules and propagate swiftinterfaces, doing so requires library evolution which changes certain semantics around things like enum frozenness and how struct initializers are handled across module boundaries. So you're forcing those constraints on builds that don't strictly need it today. For example, if I have full control over the source of modules A and B, I shouldn't have to change how I declare my enums to avoid needing `@unknown default`. Library evolution should be an opt-in choice, not the default.

It's also unclear whether the debugging experience would work if you build upstream dependencies with swiftinterfaces (thus using the implicitly built and cached "slim" swiftmodules) and then tried to debug with the "complete" swiftmodules.

If all of these issues can be resolved, then this is an interesting idea to explore, but I think we need more compiler (and debugger?) support before it's actually feasible and stable.

**Comment by keith** [comment]
> Folks don't tend to use testonly consistently and I'm not crazy about using that attribute as the trigger for -enable-testing, let alone module propagation behavior.

Do you have any other ideas on what other indicator we could use to implement this difference? This feels similar to this case for me https://github.com/bazelbuild/rules_apple/issues/321 where we want to change behavior based on what depends on you, which doesn't seem to have a solution AFAIK.

> Library evolution should be an opt-in choice, not the default.

I definitely agree, I'm not sure if we would opt into this now but as I mentioned on the other PR, assuming we will eventually support this, adding this now since it's already opt in might be ok to do, and then we'll be able to remove the library evolution constraint once Swift does.

> It's also unclear whether the debugging experience would work if you build upstream dependencies with swiftinterfaces (thus using the implicitly built and cached "slim" swiftmodules) and then tried to debug with the "complete" swiftmodules.

Yea this is a good question, I'd have to try and see what happens

> If all of these issues can be resolved, then this is an interesting idea to explore, but I think we need more compiler (and debugger?) support before it's actually feasible and stable.

Yea I'm not sure this will be able to work 100% right now, but assuming this is a place we want to move to in the future, we might be able to implement it as opt-in so we can start figuring out these open questions

**Comment by allevato** [comment]
> Yea I'm not sure this will be able to work 100% right now, but assuming this is a place we want to move to in the future, we might be able to implement it as opt-in so we can start figuring out these open questions

That's a big assumption right now, given the issues above. Emitting swiftinterface files has a concrete use case today—building distributed Swift frameworks. Consuming them in the way you're describing isn't proven yet to be stable, and I wouldn't want to take on the maintenance burden of the alternate code paths to support that until we have more confidence that it would work.

Rather than landing anything here, it would be better to just try building it out locally first and see what happens.

**Comment by keith** [comment]
> Rather than landing anything here, it would be better to just try building it out locally first and see what happens.

Sounds good. In the interest of not having to re-do the work once it is mergable, do you have a suggestion on what we should use to tell if the library is a test library and has to depend on the swiftmodules?

**Comment by keith** [comment]
In swift there is an upcoming `-enable-experimental-cross-module-incremental-build` flag that should generally solve this issue with less hacks.
