### ISSUE TITLE
swift_binary output depends on Xcode.app path

### ISSUE THREAD

**Issue by ChristopherRogers** [bazelbuild/rules_swift#320]
swift_binary can include a path from inside the Xcode.app bundle in the binary but it doesn't declare the path to Xcode.app as an input. So when the path to Xcode changes, the build output can be erroneously reused and fail to launch.

This happens when the swift_binary rule adds that path to the rpath settings on newer versions of macOS (in order to find developer dylibs like lib_InternalSwiftSyntax.dylib). The exact path used will be something like `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx`.

**Comment by allevato** [comment]
This isn't an issue specifically with `swift_binary`, but with Bazel regardless of the rule you're using. It creates a local repository with information about the Xcode(s) present on the host system, but from that point forward it doesn't detect changes to the host system unless you force it by running `bazel clean --expunge`.

There's nothing rules_swift can do here, so I'll close this out and recommend that you follow https://github.com/bazelbuild/bazel/issues/8193 (and there may be other issues filed about it as well).
