### ISSUE TITLE
Add support for `-debug-prefix-map`

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_swift#35]
Once https://github.com/apple/swift/pull/17665 makes it into a Swift release, we need to support the flag by having invocations of `swiftc` remap the Bazel execroot to `"."`. Then, users who spawn lldb at the root of their workspace will have their source files found as expected.

**Comment by JianweiWangs** [comment]
Hello, I try use this feat. but not work
I have wrote -fdebug-prefix-map=old=new into Build Phases - Compile Sources - Compiler Flags
Could you help me?
