### ISSUE TITLE
swift_import not linked with ios_unit_test

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#37]
Currently if you define a `swift_import` rule such as:

```
swift_import(
  name = "Foo",
  archives = [
    ":libFoo.a",
  ],
  swiftmodules = [
    ":Foo.swiftmodule",
  ],
)
```

And then you include that from a `swift_library` with another `swift_library` for tests:

```
swift_library(
  name = "Bar",
  srcs = glob(["*.swift"]),
  deps = [":Foo"],
)

swift_library(
  name = "BarTestsBinary",
  srcs = glob(["Tests/*.swift"]),
  deps = [":Bar"],
)
```

And finally you try to create a `ios_unit_test` bundle for this:

```
ios_unit_test(
  name = "BarTests",
  deps = [":BarTestsBinary"],
)
```

When you run `bazel test //:BarTests` you end up getting a linker error because the symbols from `Foo` are not defined. If you re-run this with `--linkopt -v`, you can see the `ld` invocation doesn't contain `-Lpath/to/Foo` or `-lFoo`. I noticed [here](https://github.com/bazelbuild/rules_swift/blob/e7b811857c7f9cf8eb874f3eefaf04acc0558b8c/swift/internal/swift_import.bzl#L43) that it seems like we might want to be propagating those flags here, but after making that change locally, it still doesn't appear that `ios_unit_test` is reading these.

Is this the correct configuration or should I be using different rules for this?

**Comment by allevato** [comment]
I think I see what's happening here.

`ios_unit_test` uses `apple_binary` underneath to link the binary. Unlike `swift_binary`, `apple_binary` is a native rule so it doesn't know anything about `SwiftInfo` provider; it can only get the libraries that need to be linked from the `Objc` provider. We make this work for `swift_library` by *also* creating and propagating an `Objc` provider with the library in it: https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/api.bzl#L626

So fixing this should just be a matter of having `swift_import` also propagate an `Objc` provider.

**Comment by keith** [comment]
Thanks for the context, I've looked into a fix a bit more for this, it looks like there might be another issue related to this ObjC vs Swift rule. It seems like the SwiftToolchainInfo created [here](https://github.com/bazelbuild/rules_swift/blob/e7b811857c7f9cf8eb874f3eefaf04acc0558b8c/swift/internal/xcode_swift_toolchain.bzl#L371-L390) may also not be propagated, leading the the linker flags to the Swift libraries not being included in the final link. Would this make sense?

I also noticed that `swift_import` takes multiple archives, and multiple swiftmodules, this seems to conflict with `new_objc_provider` which [expects](https://github.com/bazelbuild/rules_swift/blob/e7b811857c7f9cf8eb874f3eefaf04acc0558b8c/swift/internal/compiling.bzl#L347-L355) only 1 of each of these. Would it be reasonable to either remove the array support from `swift_import` and require multiple `swift_import`s per module, or possibly assume the indexes of the libraries line up with their swiftmodules in the definition?

**Comment by keith** [comment]
I've submitted an solution to this problem for discussion https://github.com/bazelbuild/rules_swift/pull/38/files

**Comment by allevato** [comment]
> I also noticed that `swift_import` takes multiple archives, and multiple swiftmodules, this seems to conflict with `new_objc_provider` which expects only 1 of each of these. Would it be reasonable to either remove the array support from `swift_import` and require multiple `swift_import`s per module, or possibly assume the indexes of the libraries line up with their swiftmodules in the definition?

I think we want to retain the ability to list multiple modules and libraries in the rule; in the future I'd like for `swift_import` to have smarter handling of framework-based modules (where you have the `Modules` subdirectory with a file for each architecture), and it's a much better user experience for the BUILD author to just `glob` those and let the compiler sort it out than to `select` the right one based on target architecture.

Likewise, requiring indices to line up is fragile, so we should avoid that.

I'll have some feedback on your PR soon—the past couple weeks have been hectic and I'm trying to get some other changes pushed out that might affect your work.
