### ISSUE TITLE
building an ios_static_framework which wraps c and c++

### ISSUE THREAD

**Issue by asa** [bazelbuild/rules_swift#377]
I am not able to build an *ios_static_framework* to extend the example in [examples/xplatform/c_from_swift](https://github.com/bazelbuild/rules_swift/tree/master/examples/xplatform/c_from_swift) so I can make a static framework to wrap c++.   The C module is not imported in the build.

I wrote up a package that makes this issue self contained here:
https://github.com/asa/bazel_static_framework_issue

I am likely doing something stupid, but I don't see a way forward. I have also tried to work with the static_framework rules in ios-bazel-users without success.   Any hints forward would be great.

**Comment by keith** [comment]
Your project builds fine for me with bazel 3.1.0 and newer versions of the rules. Please open a new issue if you're still seeing issues.
