### ISSUE TITLE
swift_library resources aren't propagated to ObjC rules

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#39]
Currently if you have a configuration like this:

```python
objc_bundle_library(
    name = "FooResources",
    asset_catalogs = glob([
      "Resources/Foo.xcassets/**",
    ])
)

swift_library(
  name = "Foo",
  srcs = glob(["Sources/*.swift"]),
  resources = [
    ":FooResources",
  ],
)

swift_library(
  name = "FooTestsBinary",
  srcs = glob(["Tests/*.swift"]),
  deps = [":Foo"],
)

ios_unit_test(
  name = "FooTests",
  deps = [":FooTestsBinary"],
)
```

The final `.xctest` bundle produced does not contain `FooResources.bundle`. It looks like this is caused by no post processing being done in the `swift_library` rule to propagated providers including these resources. It seems like some of this logic might have gotten lost since https://github.com/bazelbuild/rules_apple/pull/40

**Comment by keith** [comment]
This might be causing another issue I noticed. In this case if alongside the xcassets, I add some strings files, those strings are copied into the final binary (if I add it as a dependency of the test bundle directly) but they aren't converted to a binary plist. If this doesn't should related I can create a new issue with this example.

**Comment by keith** [comment]
I actually don't see this behavior with `ios_application`, so maybe this is specific to or intentional in `ios_unit_test`?

**Comment by allevato** [comment]
With `objc_library`, targets of kind `objc_bundle` or `objc_bundle_library` go in the `bundles` attribute, not in `resources`. Neither version of `swift_library` (the rules_apple one or the rules_swift one) have ever supported the `bundles` attribute, so I'm not surprised that the example above doesn't work.

Are you saying that you've observed bundles in `swift_library` targets used by `ios_application` working when placed in the `resources` attribute? If that does work, it's likely to be accidental and lucky at best.

**Comment by keith** [comment]
> Are you saying that you've observed bundles in swift_library targets used by ios_application working when placed in the resources attribute? If that does work, it's likely to be accidental and lucky at best.

Exactly. Maybe there was some other configuration that caused this.

Would it be reasonable in the meantime to add `bundles` support to `swift_library` and possibly `swift_import` until `data` is ready to replace these?

**Comment by allevato** [comment]
> Would it be reasonable in the meantime to add bundles support to `swift_library` and possibly `swift_import` until `data` is ready to replace these?

Fundamentally, I prefer not to add new attributes that I know are going to be deprecated and removed in fairly short order because it just causes more churn and migration headaches. The time spent supporting those attributes is time not spent implementing the "right" thing. (And it would require synchronized changes between this repository and rules_apple, which makes it a bit more of a headache.)

Do any of the resources in your bundle require knowledge of the Swift module name (i.e., any IB files or Core Data models that get their module name from the current target)? If not, you could add a dummy `objc_library` that references the bundle and then have your `swift_library` depend on that. That's a fairly inexpensive local workaround.

The strings issue is unrelated; I commented about it on that issue.

**Comment by keith** [comment]
> Do any of the resources in your bundle require knowledge of the Swift module name (i.e., any IB files or Core Data models that get their module name from the current target)

We might be able to get around this since we don't use the implicit module fields for IB files, but they are still passed the module argument so I'd have to check if anything else is relying on that.

**Comment by allevato** [comment]
700b5c9c4c17cc6bf3c3c2288309d5522a76aa7f removes the `resources` and `structured_resources` attributes from `swift_library`, now using `data` where they can be uniformly picked up by the Apple bundling rules. Closing this as no longer applicable.
