### ISSUE TITLE
Absolute paths embedded in .swiftmodule

### ISSUE THREAD

**Issue by ali-fareed** [bazelbuild/rules_swift#398]
When performing distributed builds (in which case an action's execution path is essentially random to avoid collision) or when sharing a cache between different users `.swiftmodule` files contain absolute paths. This leads to cascade rebuilds of all reverse dependencies even if no changes ave
I have tried performing the build with `--features=debug_prefix_map_pwd_is_dot` and `--features=swift.cacheable_swiftmodules`, but it does not seem to affect this behavior.
Looking at the `swiftmodule` in text mode, the values of `--working-directory` and`--fdebug-prefix-map` also embedded with absolute paths in their values. Also, it contains absolute action output paths of all swift dependencies.

This is likely an issue with the swift compiler itself, and out of scope of this repository. In that case I would appreciate any input on what could be done.

**Comment by ali-fareed** [comment]
Turns out, the problem is not new: https://forums.swift.org/t/question-absolute-paths-in-executable-swiftmodule-files/6646

It looks like the easiest solution right now is to ensure that all users of a distributed cache place the workspace at the same absolute path. For remote builds, it could be acceptable to reconstruct action's directory structure at its absolute location and implement locking to avoid conflicts when requesting the same action concurrently by multiple clients.

`.swiftinterface` files could help since they are supposed to be naturally portable, but as discussed in #316 they are suited for this particular use case at the moment.

**Comment by kastiglione** [comment]
Have you tried `llvm-bcanalyzer -dump` (which is mentioned in the swift forums post you linked)? It will show which fields of the swiftmodule contain the absolute paths.

We haven't seen any embedded paths since using cacheable_swiftmodules, so I'm curious where they're coming from in your build.

**Comment by ali-fareed** [comment]
Yes, I see them under the `<OPTIONS_BLOCK>`:
```
<XCC abbrevid=7/> blob data = '-working-directory'
<XCC abbrevid=7/> blob data = '/private/var/tmp/_bazel_ali/1b8066f0de265c99d42fe7c721d74590/execroot/__main__'
...
<XCC abbrevid=7/> blob data = '-w'
<XCC abbrevid=7/> blob data = '-fdebug-prefix-map=/private/var/tmp/_bazel_ali/1b8066f0de265c99d42fe7c721d74590/execroot/__main__=.'
```
And under `<INPUT_BLOCK>`:
```
<SEARCH_PATH abbrevid=8 op0=0 op1=0/> blob data = '/private/var/tmp/_bazel_ali/1b8066f0de265c99d42fe7c721d74590/execroot/__main__/bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-dbg/bin/submodules/Markdown'
```

Here it is said that remapping ClangImporter flags in the `OPTIONS_BLOCK` is an open question: https://github.com/apple/swift/pull/17665

**Comment by kastiglione** [comment]
Oh are you using the latest master? The cacheable_swiftmodules feature is broken, I have a PR here: #388 

I would say it's worth re-opening this issue, to track the problem. Tony hasn't commented so I don't know if that PR will Be accepted, or if another solution is preferred.

We are using that patch and it works.

**Comment by ali-fareed** [comment]
You are right, after building with opt the module does not contain any absolute paths.
I had seen your PR, but misread the condition thinking that it breaks the opt builds instead.
