### ISSUE TITLE
Alternatives to `--apple_platform_type=ios`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_swift#452]
I have a MacOS app and an iOS app in the same workspace and want to be able to build both by running `bazel build //...` (or at least not error from one or the other). I know I can set `--apple_platform_type=ios` in my build command or `.bazelrc` and successfully build my iOS targets. But I'm wondering if there's something I can specify on my `swift_library` rule to be able to successfully build my iOS and MacOS libraries in the same build command. Currently, building `//...` gives me the following errors.
```
bazel build --apple_platform_type=ios //...
```
```
ios/AppDelegate.swift:9:8: error: no such module 'UIKit'
import UIKit
```

If I build normally (for Mac) I get a similar error
```
bazel build //...
```
```
macos/AppDelegate.swift:9:8: error: no such module 'Cocoa'
import Cocoa
```

So if there's no way to tell my swift library that it's an iOS app, then is there a way to restrict building a target to specific configurations?

**Comment by keith** [comment]
Probably best to mark your swift_library targets as `tags = ["manual"]` the doing `//...` will only build your platform specific targets

**Comment by UebelAndre** [comment]
Are there examples that have iOS and MacOS in the same workspace and are buildable with the same configuration?

**Comment by keith** [comment]
I'm not sure, but here's some more specifics of my example:

```bzl
ios_application(
    ...
    deps = ["iOSAppDelegate"],
)

macos_application(
    ...
    deps = ["macOSAppDelegate"],
)

swift_library(
    name = "iOSAppDelegate",
    ...
    deps = ["SharedLibrary"],
    tags = ["manual"],
)

swift_library(
    name = "macOSAppDelegate",
    ...
    deps = ["SharedLibrary"],
    tags = ["manual"],
)

swift_library(
    name = "SharedLibrary",
    ...
    tags = ["manual"],
)
```

Something like this should work and build both the iOS and macOS applications at once.

**Comment by UebelAndre** [comment]
Is there a way to force a `swift_library` to build with an iOS toolchain?

**Comment by keith** [comment]
Only that flag. If you're using a wrapper macro you can add an underlying `apple_static_framework` rule to emulate it too.

**Comment by UebelAndre** [comment]
Is there an example of that somewhere?

**Comment by keith** [comment]
Idk. Example:

```bzl
def my_swift_library(name, ...):
    swift_library(
        name = name + ".secret",
        tags = ["manual"],
        ...
    )

    apple_static_library(
        name = name,
        deps = [name + ".secret"],
        platform_type = "ios",
        ...
    )
```

And then use `my_swift_library` instead of the default one. This can also be useful for other abstractions like defaulting `srcs` or something.

**Comment by UebelAndre** [comment]
Ah, I see! Thanks for answering all my questions 😄. The `manual` tag is the thing that gets me the behavior I'm looking for. The `swift_library` seems to be able to be built with the correct flag for ios without needing to specify command line arguments.

Thanks again for all your examples @keith
