### ISSUE TITLE
Add docs generation

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#468]
https://github.com/bazelbuild/stardoc

**Comment by alexeagle** [comment]
Maybe I can help with this, I just added stardoc to rules_docker

**Comment by keith** [comment]
that would be awesome!

**Comment by alexeagle** [comment]
By the way, now that this uses stardoc, it looks a lot better on our "g3doc for rulesets" 
https://docs.aspect.dev/rules_swift
😎
