### ISSUE TITLE
Foo.modulemaps/module.map deleted during build

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_swift#47]
When building our app with whole module optimization for all modules, we're seeing this error intermittently:

```
<unknown>:0: error: cannot open file '/private/var/tmp/.../__main__/bazel-out/darwin-fastbuild/bin/Modules/Foo/Foo.modulemaps/module.modulemap': No such file or directory
```

Using watchman we were able to see that this file was created during the build, and then deleted, assumably before it was attempted to be accessed by the dependent modules.

Our modules seem to be correctly defined as dependencies of others, but we'll still see this in the case where Foo depends on Bar, Bar's module.modulemap will be gone when building Foo.

We haven't been able to reproduce this when we pass `-j 1`

**Comment by keith** [comment]
We also don't see this when using `--sandbox_debug`

**Comment by allevato** [comment]
Can you provide a small repro case? It sounds like an issue where a path to the module map but not the file itself is being propagated, so upstream actions don't have access to it. However, the fact that it's happening intermittently is strange.

**Comment by keith** [comment]
Not sure if this is still an issue, we're side-stepping this. If others see this please comment!
