### ISSUE TITLE
Support -enable-batch-mode in Swift 4.2

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_swift#49]
Batch mode compilation was added to Swift 4.2, which provides speed-ups for non-incremental builds that are closer to the performance that people see when they use whole-module optimization.

Unlike WMO, batch mode _is_ something that makes sense to turn on unconditionally by default, so we should detect if a toolchain uses Swift 4.2 and, if so, add it to the command line.

**Comment by keith** [comment]
We can do this one now, do we want to do this conditionally based on tools version? Otherwise this should be a very simple addition

**Comment by allevato** [comment]
Yes, it should be done conditionally based on the Xcode version. And here comes #67...

**Comment by keith** [comment]
Thanks!
