### ISSUE TITLE
How to link all dependencies

### ISSUE THREAD

**Issue by omarzl** [bazelbuild/rules_swift#499]
Hello, I am new in this world of Bazel, we start to migrate our app to Bazel build system, I already did some tests but I can't understand how to link all our swift dependencies.

Here is the log of the Bazel build command and I have an objc library (Amplitude) that gets compiled and then linked to produce a `.a` library `action 'Linking libAmplitude-iOS.a'`

Then I have two swift libraries that are compiled (ObjectMapper and RxSwift) but they are not linked so the .a library is not generated. `action 'Compiling Swift module ObjectMapper'` `action 'Compiling Swift module RxSwift'`

Finally I have my main swift library (Demo) that is compiled and linked so the `libDemo.a` is generated.
`action 'Compiling Swift module Demo'` `action 'Linking libDemo.a'`

How can I make that the missing swift dependencies libraries are linked too (ObjectMapper and RxSwift)?

I searched in the documentation but I didn't find a flag or something related, also I downloaded the source code and I see that the function `_register_static_library_link_action` is called but I can't find where or why the linking step is being skipped.

Could you give some advice?

```
omarzl@mbp-omar PodfileBazel % bazel build //:Demo --python_version=PY3 --cpu=ios_x86_64 --apple_platform_type=ios --verbose_failures --sandbox_debug --subcommands
SUBCOMMAND: # //:Amplitude-iOS [action 'Compiling Amplitude-iOS/Sources/Amplitude/AMPDatabaseHelper.m', configuration: ce2c80af2670ef88fc7f8f8450d914159b05f4836d5a5f81eda8d5ca37b052eb, execution platform: @local_config_platform//:host]
SUBCOMMAND: # //:Amplitude-iOS [action 'Linking libAmplitude-iOS.a', configuration: ce2c80af2670ef88fc7f8f8450d914159b05f4836d5a5f81eda8d5ca37b052eb, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_omarzl/009f15749b719a9df685cc961e7f48c3/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=14.0 \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin \
    XCODE_VERSION_OVERRIDE=12.0.0.12A7209 \
  external/local_config_cc/libtool -no_warning_for_no_symbols -static -filelist bazel-out/ios_x86_64-fastbuild/bin/Amplitude-iOS-archive.objlist -arch_only x86_64 -syslibroot __BAZEL_XCODE_SDKROOT__ -o bazel-out/ios_x86_64-fastbuild/bin/libAmplitude-iOS.a)
SUBCOMMAND: # //:ObjectMapper [action 'Compiling Swift module ObjectMapper', configuration: ce2c80af2670ef88fc7f8f8450d914159b05f4836d5a5f81eda8d5ca37b052eb, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_omarzl/009f15749b719a9df685cc961e7f48c3/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=14.0 \
    XCODE_VERSION_OVERRIDE=12.0.0.12A7209 \
  bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/ios_x86_64-fastbuild/bin/ObjectMapper.swiftmodule-0.params)
SUBCOMMAND: # //:RxSwift [action 'Compiling Swift module RxSwift', configuration: ce2c80af2670ef88fc7f8f8450d914159b05f4836d5a5f81eda8d5ca37b052eb, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_omarzl/009f15749b719a9df685cc961e7f48c3/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=14.0 \
    XCODE_VERSION_OVERRIDE=12.0.0.12A7209 \
  bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/ios_x86_64-fastbuild/bin/RxSwift.swiftmodule-0.params)
SUBCOMMAND: # //:Demo [action 'Compiling Swift module Demo', configuration: ce2c80af2670ef88fc7f8f8450d914159b05f4836d5a5f81eda8d5ca37b052eb, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_omarzl/009f15749b719a9df685cc961e7f48c3/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=14.0 \
    XCODE_VERSION_OVERRIDE=12.0.0.12A7209 \
  bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker swiftc @bazel-out/ios_x86_64-fastbuild/bin/Demo.swiftmodule-0.params)            _
SUBCOMMAND: # //:Demo [action 'Linking libDemo.a', configuration: ce2c80af2670ef88fc7f8f8450d914159b05f4836d5a5f81eda8d5ca37b052eb, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_omarzl/009f15749b719a9df685cc961e7f48c3/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=iPhoneSimulator \
    APPLE_SDK_VERSION_OVERRIDE=14.0 \
    XCODE_VERSION_OVERRIDE=12.0.0.12A7209 \
  external/local_config_cc/libtool -no_warning_for_no_symbols -static -o bazel-out/ios_x86_64-fastbuild/bin/libDemo.a -filelist bazel-out/ios_x86_64-fastbuild/bin/libDemo.a-0.params)
Target //:Demo up-to-date:
  bazel-bin/Demo-Swift.h
  bazel-bin/Demo.swiftdoc
  bazel-bin/Demo.swiftmodule
  bazel-bin/libDemo.a
INFO: Elapsed time: 51.198s, Critical Path: 36.78s
INFO: 222 processes: 219 darwin-sandbox, 3 worker.
INFO: Build completed successfully, 232 total actions
omarzl@mbp-omar PodfileBazel % 

```

Here is the BUILD file

```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@rules_cc//cc:defs.bzl", "objc_library")

objc_library(
    name = "Amplitude-iOS",
    srcs = glob([
        "Amplitude-iOS/Sources/Amplitude/*.m",
        "Amplitude-iOS/Sources/Amplitude/SSLCertificatePinning/*.m",
    ]),
    hdrs = [
        "Amplitude-iOS/Sources/Amplitude/*.h",
        "Amplitude-iOS/Sources/Amplitude/SSLCertificatePinning/*.h",
    ],
    module_name = "Amplitude_iOS",
    sdk_dylibs = ["sqlite3.0"],
    visibility = ["//visibility:public"],
)

swift_library(
    name = "ObjectMapper",
    srcs = glob([
        "ObjectMapper/Sources/**/*.swift",
    ]),
    module_name = "ObjectMapper",
    visibility = ["//visibility:public"],
)

swift_library(
    name = "RxSwift",
    module_name = "RxSwift",
    srcs = glob(
        [
            "RxSwift/RxSwift/**/*.swift",
            "RxSwift/Platform/**/*.swift",
        ],
        exclude = [
            "RxSwift/RxSwift/Platform/**/*.swift",
        ],
    ),
    visibility = ["//visibility:public"],
)

swift_library(
    name = "Demo",
    srcs = glob(["Demo/Source/*.swift"]),
    module_name = "Demo",
    copts = ["-Onone"],
    visibility = ["//visibility:public"],
    deps = [
        "//:Amplitude-iOS",
        "//:ObjectMapper",
        "//:RxSwift",
    ],
)
```

**Comment by keith** [comment]
With static linking all the static libraries you depend on will not be combined until you link the final binary (likely an `ios_application` target)

**Comment by omarzl** [comment]
Thank you Keith, right, the final iOS app will combine all inside the executable but we want to do this Bazel migration in phases, those libraries are shared between multiple apps, we aren't ready to delete the xcprojects and use ios_application rules yet.
We would like to generate those static libs (.a) and make all the apps points to those compiled libraries.

Is there a way to do that? I saw that I could run `bazel build //:Demo` to make it compile all the dependencies (taking advantage of the parallel building) and then run for each dependency `bazel build //:RxSwift` `bazel build //:ObjectMapper` so the libraries are exported, but that is an ugly solution in my opinion.

Even if we need to modify or add code to the rules we will do it, but I can't find the right point where the linking step for Demo target is running but for RxSwift and ObjectMapper is not.

**Comment by omarzl** [comment]
As you can see in the bazel-bin directory, we have everything ready to integrate it to an Xcode project, we have the swiftdoc, swiftmodule, the module maps, the -Swift.h headers, even in the RxSwift_objs and ObjectMapper_objs folders are the .o object files, we just need that missing step to archive them in .a static lib 😞

<img width="401" alt="image" src="https://user-images.githubusercontent.com/6267487/95492636-fd882300-0960-11eb-8789-9aaf1b5f4463.png">

**Comment by keith** [comment]
You can build multiple targets at once like this: `bazel build //:Demo //:RxSwift ...`

Alternatively you can use a "fully linked" library, which you can build directly from an `objc_library` as mentioned here https://docs.bazel.build/versions/master/be/objective-c.html#objc_library

For your case I believe you would want `bazel build //:Demo_fully_linked.a`

**Comment by omarzl** [comment]
I will take a look to those options, thank you Keith!
