### ISSUE TITLE
Support alternate toolchains

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_swift#5]
Once we migrate to the proper toolchains API (#3), we should have a way to let the user easily build using a different toolchain than the default for their platform. For example, using a development snapshot or a toolchain locally built from source.

**Comment by keith** [comment]
This is doable on macOS now https://github.com/bazelbuild/rules_swift#building-with-custom-toolchains

**Comment by allevato** [comment]
And you were the one who committed it! 😄
