### ISSUE TITLE
Can't build gRPC targets

### ISSUE THREAD

**Issue by adam-rocska** [bazelbuild/rules_swift#534]
# Bazel Version

```
bazel 3.7.1
```

# BUILD contents

```
load("@rules_proto//proto:defs.bzl", "proto_library")
load(
    "@build_bazel_rules_swift//swift:swift.bzl",
    "swift_binary",
    "swift_grpc_library",
    "swift_proto_library",
    "swift_test",
)

swift_proto_library(name = "lib_swift", deps = ["@demo_proto//:lib"])

swift_grpc_library(
    name = "lib_client_swift",
    srcs = ["@demo_proto//:lib"],
    flavor = "client",
    deps = [":lib_swift"],
)

swift_grpc_library(
    name = "lib_client_stubs_swift",
    srcs = ["@demo_proto//:lib"],
    flavor = "client_stubs",
    deps = [":lib_swift"],
)

swift_grpc_library(
    name = "lib_server_swift",
    deps = [":lib_swift"],
    srcs = ["@demo_proto//:lib"],
    flavor = "server",
)

swift_binary(
    name = "bin",
    deps = [
        ":lib_server_swift",
        ":lib_client_swift",
        ":lib_swift",
    ],
    srcs = glob(["Sources/demo-backend/*"])
)
```

# About @demo_proto 

## What it is 
It's a separate repository that contains only our proto descriptions of our messages & services we plan to implement & integrate throughout our systems.

## How it's structured

* `src/proto/${sources}`, where `sources` can be any path, matching the intended package path.
* We organize proto files in a one file per message / one file per service fashion

## The `@demo_proto`'s BUILD file

```
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name                = "lib",
    srcs                = glob(["src/proto/**/*.proto"]),
    visibility          = ["//visibility:public"],
    strip_import_prefix = "src/proto",
    deps                = ["@com_google_protobuf//:timestamp_proto"],
)

```

# The error we get from running `bazel build :bin` in our experimental repo

```
INFO: Analyzed target //:bin (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/rocskaadam/src/my_company/src/my_cool_solution-backend/BUILD:26:19: output 'lib_server_swift.protoc_gen_grpc_swift/_my_company/authentication/credential.grpc.swift' was not created
ERROR: /Users/rocskaadam/src/my_company/src/my_cool_solution-backend/BUILD:26:19: output 'lib_server_swift.protoc_gen_grpc_swift/_my_company/authentication/session.grpc.swift' was not created
ERROR: /Users/rocskaadam/src/my_company/src/my_cool_solution-backend/BUILD:26:19: output 'lib_server_swift.protoc_gen_grpc_swift/_my_company/identity.grpc.swift' was not created
ERROR: /Users/rocskaadam/src/my_company/src/my_cool_solution-backend/BUILD:26:19: not all outputs were created or valid
Target //:bin failed to build
ERROR: /Users/rocskaadam/src/my_company/src/my_cool_solution-backend/BUILD:33:13 not all outputs were created or valid
INFO: Elapsed time: 0.248s, Critical Path: 0.09s
INFO: 4 processes: 3 internal, 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

# The assumed root cause

It seems like for some reason, the `swift_grpc_library` target declares all of our proto files as output, while, [according to the docs](https://github.com/bazelbuild/rules_swift/blob/master/doc/rules.md#swift_grpc_library), by design it doesn't produce outputs only for services. Quote: 

> Note that swift_grpc_library only generates the gRPC service interfaces (the service definitions) from the .proto files. 

## Mitigations we tried

1. We tried to have a separate `proto_library` target for messages & another one for services. However, `swift_grpc_library` can only work with one item in deps & one item in srcs.
2. We tried to play around with `swift_common` to make build execution hop in & out of if statements in [swift_grpc_library.bzl](https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/swift_grpc_library.bzl#L232) but since we have no clue what we're doing 😄 it didn't succeed ¯\_(ツ)_/¯ 
3. We tried to dump everything in one file as in your examples, and in that case it worked, but it's not the route we want to take.

# Disclaimers

We know our naming doesn't fit the general practice / live convention of `lib`, `bin`, `_proto`, etc. and plan to match them properly as soon as we manage to get a green build :)

If by any chance this isn't a bug, but an expected behavior, we would much appreciate some guidance on how to get past this problem within the following boundaries:
1. We'll keep message packaging. The Proto sources shall be used by Java, PHP, and C# programs for example.
2. We'll keep the one file per message / one file per service organiztation. The system is big & will grow even bigger. It helps us to navigate & understand things better if they're all separated instead of one big `.proto` file per service (as in this repo's examples)
3. We'll keep the `proto_library` target in the proto repo, while we expect its user repos to declare their own `${language}_proto_library` targets depending on this common parent node.

**Comment by adam-rocska** [comment]
Update: Forgot to mention, that we also found an approach where each proto file has a `proto_library` target defined, and therefore dependencies and everything managed in two places (in the proto files via import & in the BUILD files) which is less than ideal; we'd avoid that suggestion as well.

* Google books source : https://books.google.hu/books?id=J_7EDwAAQBAJ&pg=PA183&lpg=PA183&dq=%22swift_grpc_library(%22&source=bl&ots=oJEuxy-PCT&sig=ACfU3U0v05y4yaeSxWKh-hgFKLxmqCAY6w&hl=en&sa=X&ved=2ahUKEwjVv6uc-sDtAhVnpYsKHbsVBooQ6AEwBHoECAcQAg#v=onepage&q=%22swift_grpc_library(%22&f=false)

StackB source:
* [Proto definitions](https://github.com/stackb/rules_proto/blob/3ca0bf4156d189d38f5b049c2c5de891191fda4f/example/proto/BUILD.bazel)
* [Swift grpc usage](https://github.com/stackb/rules_proto/blob/3ca0bf4156d189d38f5b049c2c5de891191fda4f/example/swift/swift_grpc_library/BUILD.bazel)

This technique would make development & maintenance cumbersome.

**Comment by adam-rocska** [comment]
Update: Before the suggestion would come in to just bow in & create one `proto_library` target per proto file as per the ["recommended" way of doing things](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library), I must emphasize we know, that some people somewhere think it's a great idea, and it is the **recommended** way. But:
* We think differently; we don't think it's a great idea.
* If it's the **recommended** way, it implies it should work with different approaches (like the lazy glob one we used to use during the bazel 0.x era)

**Comment by thomasvl** [comment]
So the problem you hit is actually in the grpc library (well, in the plugin they provide) and not in this rule.  The `swift_grpc_library` rule is assuming the grpc plugin will make the files for every .proto file it is asked to generate for.  It sounds like the grpc plugin only generates sources when the file contains Services; there is no way for the rule to _inspect_ the file to figure out which ones have Services.

So to support your desire, you need to file an issue with the grpc library/plugin to ensure they generate a file for *every* proto file they are requested to generate from and not just the ones that have Services.

You also could work around this not just by having one proto file per `proto_library`, but instead by ensuring the files with services are one `proto_library` and all supporting proto files can be in another `proto_library`.

**Comment by adam-rocska** [comment]
Thanks @thomasvl

**Comment by adam-rocska** [comment]
We ended up writing a "pre-build script" that's to be executed in our repository containing the proto files.
It recursively goes through the proto sources, and generates one `proto_library` call per proto file, extracting & transforming the bazel dependencies from the proto files' `import` statements.

This way we follow the "recommended" approach, and also won't have to manually maintain proto definitions & dependencies twice.

@thomasvl thanks for the clarification & most importantly thank you for your time! 
I guess we'll have to stick to this workaround until there's another paradigm shift in the future ¯\_(ツ)_/¯
