### ISSUE TITLE
Question: Is there a forum or slack channel?

### ISSUE THREAD

**Issue by marvin-hansen** [bazelbuild/rules_swift#536]
Hi,

I'm building a set of microservices with Swift & gRPC in a small project and for a number of reasons, I'm switching to Bazel to build Swift. Among other things, I actually have the very real problem of unreasonable slow swift build time in docker. Outside docker, swift build isn't exactly fast either, but it seems that inside docker, build caching doesn't work at all so swift build pulls & builds all dependencies each single time and that takes > 8 minutes instead of a few seconds for a proper incremental build.  Building larger services with more dependencies is already on the brink of impractical at this point thus the switch to Bazel. I guess that's a common story. 

However, I'm struggling with getting my head around writing and using proper BUILD files for a local build. While the Bazel documentation itself is quite comprehensive and in very good shape, making the Swift rules work for the first time, however, is a bit of a hazzle due to the steep learning curve and few tutorials out there. I did a bit of web search but could not find a slack channel or user forum for Swift on Bazel where I could ask a few questions to figure out if I am heading into the right direction. 

And that's my actual question, is there a forum, glitter, or slack channel for swift/bazel to ask questions?

**Comment by keith** [comment]
Bazel has a slack group linked here https://bazel.build/support.html

**Comment by marvin-hansen** [comment]
Thanks a lot. Will close this issue.

**Comment by marvin-hansen** [comment]
Solved.

**Comment by wiwa** [comment]
This doesn't seem to be true?

**Comment by keith** [comment]
Guess it was removed from that page, the URL to join is https://slack.bazel.build/
