### ISSUE TITLE
Is it OK to disable the swift worker on CI builds?

### ISSUE THREAD

**Issue by jagobagascon** [bazelbuild/rules_swift#559]
I have a Github Actions on a macOS container to build a simple Swift library, and compiling `protobuf` for the swift worker is taking about 80% of the build time.

I managed to skip it by using `--define RULES_SWIFT_BUILD_DUMMY_WORKER=1 --strategy=SwiftCompile=sandboxed` which massively speeds up the build. But it is not a documented feature so I'm afraid it may work in the future.

I want to keep the builds times as low as possible, cause Github macOS runners consume 10 times more minutes than linux runners.

**Is it OK to use this flag?**
If so, could it be added to the documentation?
If not, maybe this would also help? https://github.com/bazelbuild/rules_swift/issues/516

**Comment by thii** [comment]
Depending on your project's needs, if you don't want Bazel to compile your Swift code using the swift compilation worker, I think it's fine to use the flag and set the `SwiftCompile` strategy to something other than `worker` (that is, either `local`, `sandboxed` or `remote`). The flag was originally intended for running internal integration tests, so it was not documented, but I don't think it's going away anytime soon. The following comment should explain it in more details:

https://github.com/bazelbuild/rules_apple/blob/d5446ff785288b16075eacc6d1516c89ae6da573/.bazelrc#L21-L28

A related change (1ef4601bacd625d77915758c553dd8b62b09c64c) just landed yesterday and should reduce this overhead a bit.

https://github.com/bazelbuild/rules_swift/issues/516 would definitely help, when implemented.

**Comment by jagobagascon** [comment]
I'll keep it then. Thanks!

But may I suggest a change?

I understand that using the worker does not add any value on automated environments (like a CI server) and developers would benefit from faster build times by disabling it. So I think that adding a simpler way of running the compiler in a "CI friendly" manner would be helpful. 

`npm` for example has `npm ci`: "meant to be used in automated environments" and also runs faster by "skipping certain user-oriented features".

I'm kind of new to Bazel so I'm not sure about this but could it be simplified to a single flag?
`--define RULES_SWIFT_CI_MODE`

**Comment by keith** [comment]
FYI using the worker on CI could actually be beneficial if you do not clean CI between builds. In general this has some risk but could increase performance. In the meantime this flag isn't considered public API so it could break for this use case in the future. The real solution to this issue long term is https://github.com/bazelbuild/rules_swift/issues/516
