### ISSUE TITLE
Switch to using lambda when the minimum supported Bazel version by rules_swift supports it

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_swift#568]
Some Swift toolchain action configurators in the `upstream` branch use lambda (for instance, configurators for `additional_objc_copts` and `additional_swiftc_copts`), but this feature is not yet available in any official Bazel release.

**Comment by thii** [comment]
Done in https://github.com/bazelbuild/rules_swift/pull/721

**Comment by brentleyjones** [comment]
Sorry I didn't see this.
