### ISSUE TITLE
worker swiftc actions are missing standard error

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/rules_swift#640]
When I hit an error in a swift compiler action, standard error is gone. 

FWIW: to help narrow this down, I have fixed the bug by reverting:
https://github.com/bazelbuild/rules_swift/pull/633
and
https://github.com/bazelbuild/rules_swift/pull/634

**Comment by brentleyjones** [comment]
Thanks. I'll see what I messed up there.

**Comment by jerrymarino** [comment]
@brentleyjones ah thanks for looking into it! For now, I've just reverted these in the fork really looking forward to the new feature though 👍

**Comment by brentleyjones** [comment]
Fixed by https://github.com/bazelbuild/rules_swift/pull/642.

**Comment by jerrymarino** [comment]
@brentleyjones thanks for the quick fix ❤️ ! I'm going to test this out a bit this morning on rules_ios as well
