### ISSUE TITLE
rules can not load success ,  I do not kown what's wrong

### ISSUE THREAD

**Issue by SnailLoveSmile** [bazelbuild/rules_swift#660]
Starting local Bazel server and connecting to it...
INFO: Repository build_bazel_rules_apple instantiated at:
  /Users/apple/Desktop/tulsi/WORKSPACE:3:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:1181 is not a valid URL
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp9259926269861362842/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp9259926269861362842/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp9259926269861362842/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
INFO: Elapsed time: 19.118s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by tinder-maxwellelliott** [comment]
This google groups post can help you setup your proxy variables for Bazel https://groups.google.com/a/onosproject.org/g/onos-dev/c/ARwK2x_Fh24

(This is not an issue with `rules_swift`, it is actually an issue with Bazel itself, so it probably makes sense to close this ticket.)
