### ISSUE TITLE
Protobuf linked when building Swift?

### ISSUE THREAD

**Issue by nganhkhoa** [bazelbuild/rules_swift#661]
Environment:
ObjC++, C++ project without any Protobuf rules.

Steps:
- Add Swift to bazel WORKSPACE, through rules_apple -> swift_dependency
- Add a swift target, `swift_library`
- `bazel build`

Current behaviour:
Bazel link protobuf, also requires proto in WORKSPACE

Expected behaviour:
Do not link protobuf if not required.

I don't know why protobuf is linked when adding Swift. Linked with Protobuf is mostly dead code, but enlarge the binary.

**Comment by keith** [comment]
Are you saying protobuf is ending up as part of your binary, or that you see it being built during the process?

**Comment by keith** [comment]
If it's the latter see https://github.com/bazelbuild/rules_swift/issues/516 but the gist is to build swift there's some proto based communication on the bazel side

**Comment by nganhkhoa** [comment]
I saw the protobuf linking on bazel. I haven't check the binary for protobuf. Let me check.

**Comment by nganhkhoa** [comment]
On a non-stripped binary, using `nm` I cannot detect any function of protobuf.
On a more consise bazel log (`-s` option), I see bazel building protobuf and displaying `[for host]`.

Bazel compiles `@com_github_protocolbuffers_protobuf//:protobuf` and `protobuf_lite`

I don't know why protobuf is used internally in swift rules. But if that is the case, then I think there is no problem.

On the performance note, compiling the whole protobuf is not effective and I would switch to JSON.

How can I change to not use protobuf anymore? Will there by any conflict if I use rules_apple (shipped with rules_swift) and add a git_repository to where JSON is supported?

**Comment by keith** [comment]
there is no supported wait to avoid this today, but note that once it is built once, as long as your environment stays the same, it won't be rebuilt. follow https://github.com/bazelbuild/rules_swift/issues/516 for that resolution
