### ISSUE TITLE
Build error on Xcode13 with bitcode enabled ("not all outputs were created or valid")

### ISSUE THREAD

**Issue by rsahara** [bazelbuild/rules_swift#682]
On Xcode13 beta5, building with `--apple_bitcode=watchos=embedded` (for submitting the app to Testflight) generates this error in our project:

```
(...)
10:10:20 warning: ignoring -incremental; output file map has no master dependencies entry ("swift-dependencies" under "")
10:10:20 (10:10:20) ERROR: WatchModule/BUILD:25:23: output 'WatchModule/LoggingWatch_objs/Sources/Logging/Locks.swift.o' was not created
(... Same error for the other files contained in the same directory ...)
10:10:20 (10:10:20) ERROR: WatchModule/BUILD:25:23: Compiling Swift module Logging failed: not all outputs were created or valid
10:10:20 Target //:App failed to build
```

Does anyone have the same issue, or does anyone have some information about this?

- No problems with Xcode12.5.1.
- No problems with Xcode13beta5 & without bitcode (in-house builds).
- Disabling WMO changes the error to: `<unknown>:0: error: error opening input file '/var/folders/18/y9f4zd3s7k5bc3nnmg744ry80000gp/T/TemporaryDirectory.xbjsQg/Locks-1.bc' (No such file or directory)`. (Edit: when `--features=swift.vfsoverlay` is specified.)

**Comment by rsahara** [comment]
The output filename has maybe changed with Xcode13 ><

I tested with
- combinations of `-embed-bitcode`, `-num-threads`, `-whole-module-optimization`,
- output file map:
```
{
    "mofu.swift": {
        "object": "mofu.swift.o"
    }
}
```

The generated files on Xcode12.5.1:
bitcode & wmo & threads: mofu.swift.o
bitcode & wmo: mofu.swift.o
bitcode & not-wmo: mofu.swift.o
no-bitcode & wmo & threads: mofu.swift.o
no-bitcode & wmo: **mofu.o**
no-bitcode & not-wmo: mofu.swift.o

Same on Xcode13:
bitcode & wmo & threads: **mofu-1.o**
bitcode & wmo: **mofu.o**
bitcode & not-wmo: mofu.swift.o
no-bitcode & wmo & threads: mofu.swift.o
no-bitcode & wmo: **mofu.o**
no-bitcode & not-wmo: mofu.swift.o

**Comment by keith** [comment]
Looks like this might be a "works as intended" issue based on the comments on that issue (although you can probably temporarily revert back to the old driver by passing `--swiftcopt=-disallow-use-new-driver` if you need to)

but what should we change here? have you diffed the output file maps produced by Xcode 13 with the new driver?

**Comment by rsahara** [comment]
Thank you, passing `-disallow-use-new-driver` works, as a workaround. (I was using another workaround: disabling WMO for watch modules, but it needed a lot of changes...)

I just noticed that adding the "llvm-bc" key like this fixed the problem with Xcode13beta5 compiler.
```
{
    "mofu.swift": {
        "llvm-bc": "mofu.swift.bc",
        "object": "mofu.swift.o"
    }
}
```

There were no differences between the output file maps produced by Xcode13 and Xcode12.5.1 (same keys); in fact they include "llvm-bc" even when bitcode isn't used.
rules_swift doesn't declare the ".bc" file in the output file map, and for some reasons maybe the new driver needs this key in order to generate the object file in the specified path, I don't know...
