### ISSUE TITLE
Importing `swift_library` to `objc_library` 

### ISSUE THREAD

**Issue by wendyliga** [bazelbuild/rules_swift#707]
AFAIK, when swift_library is being used for objc, we enable `generates_header` to generate `module-Swift.h`.
based on this simple example below, I am unable to import swift library to objc both importing bridging header or importing module directly
```objc
#import "<EmptySwift/EmptySwift-Swift.h>" //  fatal error: '<EmptySwift/EmptySwift-Swift.h>' file not found
@import EmptySwift; //  fatal error: module 'EmptySwift' not found
```
https://github.com/wendyliga/simple_bazel

am I missing something?

**Comment by keith** [comment]
`#import "ios/EmptySwift/EmptySwift-Swift.h"` should work in your case. There's an example over here https://github.com/bazelbuild/rules_swift//blob/f1f4f6f668bc7c67adee017c46ada2121c471f8e/examples/apple/objc_interop/main.m#L20-L20

**Comment by thii** [comment]
Another way is to add the generated header's parent directory to the `objc_library` target's header search paths:

```starlark
copts = ["-I$(BINDIR)/ios"],
```

**Comment by wendyliga** [comment]
thank you for the fast response, will try your suggestion
