### ISSUE TITLE
Accessing modulemap from Swift Provider

### ISSUE THREAD

**Issue by wendyliga** [bazelbuild/rules_swift#709]
is there any way to access the generated `modulemap` from `swift_library`
the `modulemap` is place on `module_context.clang.module_map` but currently is not being used by any provider?

**Comment by wendyliga** [comment]
maybe place it on objc_provider.module_map?

**Comment by wendyliga** [comment]
the idea is something like this https://github.com/bazelbuild/rules_swift/pull/710

**Comment by thii** [comment]
Can you provide an example on what you are trying to do?

**Comment by wendyliga** [comment]
@thii i create custom rule to import all `modulemap` from objc transitive deps, so my objc library rule can depend on `swift_library` without needing custom copts to work.

the problem as I mentioned above is the generated `modulemap` on swift_library is nowhere to be accessible, so I purpose to put it on objc_provider

**Comment by thii** [comment]
Have you taken a look at `SwiftInfo`? I think what you want is already available there.

**Comment by thii** [comment]
Each module in the `transitive_modules` depset contains a `clang` struct which you can use to collect the module map.

**Comment by wendyliga** [comment]
right, will use that instead
