### ISSUE TITLE
protoc error when using `universal_binary` on x86_64

### ISSUE THREAD

**Issue by codeman9** [bazelbuild/rules_swift#762]
I added the flag `--@build_bazel_rules_swift//swift:universal_tools` to my `bazel build` command on my Intel `x86_64` machine and observed the following error:

```
fatal error: /Applications/Xcode-13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo:
  bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-73c1c77022a6/bin/external/com_google_protobuf_protoc_macos_x86_64/protoc.exe and
  bazel-out/darwin_x86_64-opt-exec-2B5CBBC6-ST-3246aae600a0/bin/external/com_google_protobuf_protoc_macos_x86_64/protoc.exe
  have the same architectures (x86_64) and can't be in the same fat output file
```

I think this is due to the logic in the `rules_proto` select. A `rules_swift` patch to `rules_proto` was introduced here: https://github.com/bazelbuild/rules_swift/pull/751 . The resulting `rules_proto` `BUILD` file looks like this:

```
load(
    "@build_bazel_apple_support//rules:universal_binary.bzl",
    "universal_binary",
)
load("@rules_proto//proto:defs.bzl", "proto_lang_toolchain")

# This has to be named `protoc` because native rules refer to
# `@com_google_protobuf//:protoc` in their implementation.
alias(
    name = "protoc",
    actual = select({
        "@build_bazel_rules_swift//swift:universal_tools_config": ":universal_protoc",
        "//conditions:default": ":single_arch_protoc",
    }),
    visibility = ["//visibility:public"],
)

universal_binary(
    name = "universal_protoc",
    binary = ":single_arch_protoc",
    visibility = ["//visibility:public"],
)

# Use precompiled binaries where possible.
alias(
    name = "single_arch_protoc",
    actual = select({
        ":linux-aarch64": "@com_google_protobuf_protoc_linux_aarch64//:protoc",
        ":linux-ppc": "@com_google_protobuf_protoc_linux_ppc//:protoc",
        ":linux-s390x": "@com_google_protobuf_protoc_linux_s390_64//:protoc",
        ":linux-x86_32": "@com_google_protobuf_protoc_linux_x86_32//:protoc",
        ":linux-x86_64": "@com_google_protobuf_protoc_linux_x86_64//:protoc",
        ":macos-x86_64": "@com_google_protobuf_protoc_macos_x86_64//:protoc",
        ":windows-x86_32": "@com_google_protobuf_protoc_windows_x86_32//:protoc",
        ":windows-x86_64": "@com_google_protobuf_protoc_windows_x86_64//:protoc",
        "//conditions:default": "@com_github_protocolbuffers_protobuf//:protoc",
    }),
    visibility = ["//visibility:public"],
)

...
```

On my M1 Mac, the select falls through to the `//conditions:default` and works as expected. On the Intel Mac, the `:macOS-x86_64` condition is selected and the error above is seen. Deleting the `:macos-x86_64` line and forcing the fall through to the default works as expected but this doesn't seem like the correct solution here.

**Comment by thii** [comment]
You have to have a [platform_mappings](https://docs.bazel.build/versions/main/platforms-intro.html#platform-mappings) file, otherwise the cpu won’t change.

**Comment by codeman9** [comment]
@thii Can you share an example? I'm not sure what to map to which that will work on both my M1 and Intel Macs.

**Comment by thii** [comment]
Here's an example:

1. Declare an execution platform that will be used for the build, e.g. in the top-level BUILD file:
```starlark
platform(
    name = "macos_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:macos",
    ],
)
```

2. Add a `platform_mappings` file to the top-level directory. This is required now because Apple rules still use the `--cpu` flag.
```
platforms:
  //:macos_x86_64
    --cpu=darwin_x86_64

flags:
  --cpu=darwin_x86_64
  --apple_platform_type=macos
    //:macos_x86_64
```

3. Enable the `--@build_bazel_rules_swift//swift:universal_tools` flag, e.g in `.bazelrc`:
```
build --@build_bazel_rules_swift//swift:universal_tools
```

4. Tell Bazel to use the new platform as the execution platform. This can be done in either of the following 3 ways:

    a. Register it in your WORKSPACE:

    ```
    register_execution_platforms("//platforms:macos_x86_64")
    ```

   b. Use the `--extra_execution_platforms` flag.

    ```
    # .bazelrc
    build --extra_execution_platforms=//:macos_x86_64
    ```

    c. Change the `--host_platform`:

    ```
    # .bazelrc
    build --host_platform=//:macos_x86_64
    ```

**Comment by codeman9** [comment]
@thii Thank you so much for your example! I managed to get this working as expected with:

1. `platform_mappings` file:

```
platforms:
  //:macos_x86_64
    --cpu=darwin_x86_64

  //:ios_x86_64
    --cpu=ios_x86_64

flags:
  --cpu=darwin_x86_64
  --apple_platform_type=macos
    //:macos_x86_64

  --cpu=ios_x86_64
  --apple_platform_type=ios
    //:ios_x86_64
```

2. Top-level `BUILD` file:

```
platform(
    name = "macos_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:macos",
    ],
)

platform(
    name = "ios_x86_64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:ios",
    ],
)

```

3. Adding `  --host_platform=//:macos_x86_64` to the build invocation. 

Without the `ios_x86_64` mapping, I see the following error:

```
ERROR: /BUILD:3:20: Linking MyModule/MyModule_bin failed: (Aborted): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang @bazel-out/ios-x86_64-min12.0-applebin_ios-darwin_x86_64-dbg-ST-b6d322bc01c9/bin/MyModule/MyModule_bin-2.params
ld: warning: directory not found for option '-F/Applications/Xcode-13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/Developer/Library/Frameworks'
ld: in external/A/A.framework/A(A.o), building for macOS, but linking in object file built for iOS Simulator, file 'external/A/A.framework/A' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thii** [comment]
I just verified, looks like the mappings for iOS cpus are also required. (We have them in our platform_mappings but I thought they were no-op.)

**Comment by keith** [comment]
I think this was figure out? If so should we close this with a summary?

**Comment by thii** [comment]
Yes, I think this is resolved. Please reopen if not.

To summarize, a [platform mappings file](https://bazel.build/concepts/platforms-intro#platform-mappings) is required when building with `--@build_bazel_rules_swift//swift:universal_tools`.
