### ISSUE TITLE
Switching from swift_library to prebuilt .framework uses outdated module

### ISSUE THREAD

**Issue by polac24** [bazelbuild/rules_swift#765]
When a swift module is built from sources and later integrated as a prebuilt .framework, previously generated .swiftmodule is still visible to swiftc (e.g via some other target that is still built from sources in a module) and the historical version is always used, even the new one is correctly exposed via apple_static_framework_import.
Sample project: https://github.com/polac24/BazelSourceFramework

Would it be possible to delete previously generated outputs (like .swiftmodule) if a target changes its output files.

Notes:
* This problem exists for the non-sandboxed build, it works fine with `--strategy=SwiftCompile=sandboxed`
* A workaround suggested in #344 to have one swift_library per package works fine

**Comment by keith** [comment]
Yea I think the core fix here is https://github.com/bazelbuild/rules_swift/issues/344 which is likely only going to be fixed by explicit modules

**Comment by thii** [comment]
I think it worked as expected? If you have two swiftmodules with the same name in search paths, how does the compiler know which one to use?

Bazel never removes dead files by itself. But you could hack it with a genrule, e.g.:

```starlark
genrule(
    name = "empty",
    outs = ["empty.swift"],
    cmd = "rm -f $(RULEDIR)/MyModule.swiftmodule && touch $@",
)
```

and add `empty` to `parent`'s `srcs`.

**Comment by polac24** [comment]
@thii, yes, it is not an unexpected swift behavior to use any available module. That is rather a limitation caused by non-explicit modules that @keith pointed out.

Thanks for the tip, I get the point. It would require some extra work to cover a case when switching back and forth, e.g. source -> framework -> source -> framework (plausible on a CI machine) as `:empty` would be cached eventually.

> how does the compiler know which one to use?

AFAIR, compiler searches all paths one-by-one in the order we pass args, so if we make sure to pass a dir with`.framework` paths before `bazel-out/...`, swift would take the .framework and fallback to the source-generated .swiftmodule if missing. Very ugly so probably we will workaround the limitation with "one target per module".

**Comment by thii** [comment]
From the comments, looks like this is resolved, so I'm closing this. Please reopen if not.
