### ISSUE TITLE
Objc Interoperability: Use Objc API from the same module

### ISSUE THREAD

**Issue by imWildCat** [bazelbuild/rules_swift#769]
In the [`objc_interop`](https://github.com/bazelbuild/rules_swift/tree/master/examples/apple/objc_interop) example, we need to import the objc module in Swift code: https://github.com/bazelbuild/rules_swift/blob/master/examples/apple/objc_interop/Printer.swift#L16

Is there any solution to merge the `objc_library` into `swift_library`?

**Comment by imWildCat** [comment]
Looks like either <https://github.com/bazel-ios/rules_ios> or <https://github.com/line/rules_apple_line> can help.

**Comment by thii** [comment]
I've tried both of them, all worked. What was the problem?
