### ISSUE TITLE
Fails to build macOS, iOS, tvOS Targets

### ISSUE THREAD

**Issue by nchavez324** [bazelbuild/rules_swift#790]
Hello,

I have a very simple repo which demonstrates failed compilation on macOS, iOS, and tvOS, using a single `swift_library` with the most basic example app on Bazel 5.1.0 and Xcode 13.3: https://github.com/nchavez324/swift_bug

I've also provided an Xcode project that builds these targets perfectly. The end issue seems to be:

```shell
Compiling Swift module app_uikit_main failed: (Exit 1): worker failed: error executing command
```
```shell
swift_worker: Could not copy bazel-out/ios-x86_64-min9.0-applebin_ios-ios_x86_64-fastbuild-ST-5a1b1e15dd4d/bin/_swift_incremental/app/uikit_main_objs/uikit/AppDelegate.swift.partial_swiftmodule to bazel-out/ios-x86_64-min9.0-applebin_ios-ios_x86_64-fastbuild-ST-5a1b1e15dd4d/bin/app/uikit_main_objs/uikit/AppDelegate.swift.partial_swiftmodule (errno 2)
```

But you can read the repo's README for the full blaze build error log and repro steps.

**Comment by brentleyjones** [comment]
You need to declare the rules_swift version before rules_apple, otherwise you get the version that rules_apple is pinned to. In this case you are actually using rules_swift 0.24.0, which doesn't have the bug fix that is in 0.27.0.

**Comment by nchavez324** [comment]
I see, thanks this worked for me! Should the guidance here be updated then?

https://github.com/bazelbuild/rules_apple#quick-setup

**Comment by nchavez324** [comment]
Nevermind, the WORKSPACE code sample in the Rules Apple Quickstart works perfectly. Thanks Brentley!
