### ISSUE TITLE
`swift_binary` doesn't encode minimum_os_version for cache hits

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/rules_swift#794]
If you use `--{host_,}macos_minimum_os=`, that information doesn't impact how the dependent `swift_library`s are cached. This results in cache poisoning. I think this is because `swift_binary` doesn't use a transition, so the minimum os version isn't encoded in the path, and there isn't an environment variable for the target triple. I'm confused on why the change in the `params` file isn't enough to cause the cache key to be different.

I tried a simple fix of setting an environment variable on `all_tool_configs`, which worked for compilation, but the linking step still pulled down down previously cached archives.

**Comment by keith** [comment]
Should we be able to see this through some `aquery` / `cquery`? I did a quick test with aquery and the `configuration` key did differ when I added the flag

**Comment by brentleyjones** [comment]
I don't think it shows up with query. gRPC log will show the same action digest though.

**Comment by keith** [comment]
Did you ever debug this one more?

**Comment by brentleyjones** [comment]
I haven't. I've been bit by it a couple more times since then though.

**Comment by brentleyjones** [comment]
Let's keep this open until that ships.
