### ISSUE TITLE
Swift incremental can get into a weird state where it constantly fails to compile

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/rules_swift#819]
In one of my workflows I have rapidly cancelling builds. It seems that this can get the Swift incremental storage into a weird state where subsequent builds fail to compile:

```
Failed to copy bazel-out/darwin_x86_64-dbg-ST-1c975e2849a6/bin/external/com_github_tadija_aexml/AEXML.swiftdoc for incremental builds, maybe it wasn't produced?
```

And in the incremental storage area there are no `swiftdoc`, `swiftmodule`, or `swiftsourceinfo` files.

The only way I can fix it is with `bazel clean`. Sadly with my workflow, that isn't an easy thing to do.

**Comment by keith** [comment]
We can technically remove the errors here, but it would likely paper over a different issue

**Comment by brentleyjones** [comment]
Ohh, it's a real issue. Nothing is produced. It just shouldn't be silently failing.

**Comment by tinder-maxwellelliott** [comment]
I have seen this same issue as well on some jobs, playing around with clean now to see if that helps out

**Comment by keith** [comment]
Through some offline convo with @brentleyjones I think this https://github.com/bazelbuild/rules_swift/pull/829 might fix it, but am not entirely sure since it's intermittent. If someone can reliably repro and test this that would be great
