### ISSUE TITLE
Upgrading gRPC to 1.X series causes import problems

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_swift#827]
I’ve got the beginnings of a patch to upgrade gRPC past version 1.0.

I fought through getting the cc_library stuff working and I’m now able to build `@com_github_grpc_grpc_swift//:GRPC` which is the target I’ve associated with the `GRPC` swift package (see https://github.com/grpc/grpc-swift#swift-package-manager to confirm this is the newest import path). 🎉 

Now, when I build, I get results like this https://app.buildbuddy.io/invocation/5ce44196-0107-40ac-862f-ecb8796a08e4#log where it doesn’t implicitly have the import for RulesSwift_Examples_Grpc_EchoRequest. I attempted to solve this by forcing an explicit import examples_xplatform_grpc_echo_proto_swift by modifying 

https://github.com/achew22/rules_swift/blob/6d8ad55e36b484dadb13bc76669e39e55e8080db/swift/internal/swift_grpc_library.bzl#L251 to be

```
# Yes, I know this matches all of them, I just wanted to have a quick way to test it out in each mode
if ctx.attr.flavor in ["server", "client", "client_stubs"]: 
```

I get a different result where it appears to not actually have the dependency as an edge (??? very unsure here)

https://app.buildbuddy.io/invocation/79e7bd35-1a70-4f8f-8bcf-de59f423a422#log

Here is the diff (sans the flavor change).
https://github.com/bazelbuild/rules_swift/compare/master...achew22:upgrade_grpc?expand=1

I have to admit that the thing I am the least understanding about swift at this point is the import/module system. Do you have any pointers to reference material on what I could do to learn more about fixing this?

**Comment by achew22** [comment]
@keith, sorry to directly @ you, but do you have any idea on this one? I've spent more than a few days staring at this, but I'm unable to figure out the modulemap in swift. Do you have any pointers?

**Comment by keith** [comment]
Sorry, this was on my list but I'm glad you figured it out!
