### ISSUE TITLE
Question: Public VS internal API of rules_swift 

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/rules_swift#891]
Hello! Would anyone be opposed to moving the `internal` API imports in rules_swift to "public" and clarifying the  API contract rule_swift is aiming to provide? Today rules_swift has doc called API: [`swift_common.compile`](https://github.com/bazelbuild/rules_swift/blob/master/doc/api.md#swift_commoncompile) but the symbols have to be imported from an internal directory

The context for this issue is we use `swift_library` to help compile swift code in `rules_ios` - a ruleset that allows you to easily compile iOS code with Bazel and more.

Because we call `swift_library` it's difficult to optimize. `swift_library` forces us to add logic in the loading phase which isn't flexible and balloons the target graph.  Post `swift_library` I can imagine attempting to use some of the helper functions in `rules_swift` e.g. we might reuse some of the "API" starlark helpers like `Toolchain`, `swift_common.compile` , and `swift_common.precompile_clang_module`!

**Comment by thomasvl** [comment]
Drive by - what symbols have to be imported from the internal directory?  [`swift_common`](https://github.com/bazelbuild/rules_swift/blob/master/swift/swift.bzl#L94) is already publicly exposed, which is why it is documented.

**Comment by jerrymarino** [comment]
@thomasvl It looks like most of our future usage is now a public API e.g. added to `swift/swift.bzl`! Mainly, we've been working to use some of these APIs when adding [PCM compiling](https://github.com/bazel-ios/rules_ios/pull/554/files#diff-890210eada2bb51dbdc2780a6602b9d4956d7c9aff7559cb1f1e8e3f4bbc60e1R2) and simplifying our target graph.

We'll have to take stock on every symbol, but there are a number of helpers we're using: e.g.. `"@build_bazel_rules_swift//swift/internal:attrs.bzl" -> "swift_library_rule_attrs"`. Off the top of my head, I imaged calling `swift_libary_rule_attrs` was necessary in practice where _public_ APIs - have constraints on the rule: e.g. via `ctx.attrs`.

**Comment by jerrymarino** [comment]
Thanks for clarifying 👍
