### ISSUE TITLE
Improve interoperability with C libraries

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_swift#9]
Right now, users have to write an explicit `swift_c_module` target to have Swift code depend on C code in a `cc_library`.

We might be able to just use an aspect to generate a module map from the library's public headers, using the same (but awful) auto-mangled module name that we use for `swift_library` targets based on their path in the workspace. Then Swift code would just add a dependency directly to the `cc_library` and import it.

**Comment by allevato** [comment]
This was done way back in ec79b09d4c79fc90fa6fd1bab9ee98f5a45197c5.

**Comment by keith** [comment]
This is awesome! This or some other change seems to have fixed https://github.com/bazelbuild/rules_swift/issues/52 too
