### ISSUE TITLE
Duplicate `main` symbol when using `@main` in `swift_library` & `swift_test`

### ISSUE THREAD

**Issue by luispadron** [bazelbuild/rules_swift#911]
I've got a fairly simple `swift_library` I'm trying to test with `swift_test`. In the `swift_library` target we use `@main` to define the main entry point on a `struct`. 

When running the `swift_test` that depends on the `swift_library` we get the following error:

```
duplicate symbol '_main' in:
    bazel-out/darwin_arm64-dbg/bin/Tools/BazelPostWrapper/libBazelPostWrapperTests.lo(BEPEventTests.swift.o)
    bazel-out/darwin_arm64-dbg/bin/Tools/BazelPostWrapper/libBazelPostWrapper.a(BazelPostWrapperCommand.swift.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Looks like because the library defines a main entry point and so do the tests we get this error. 

Here is what my BUILD file looks like:

```
load(
    "@build_bazel_rules_swift//swift:swift.bzl",
    "swift_binary",
    "swift_library",
    "swift_test",
)

swift_library(
    name = "BazelPostWrapper",
    srcs = glob(["Sources/**/*.swift"]),
    module_name = "BazelPostWrapper",
)

swift_test(
    name = "BazelPostWrapperTests",
    srcs = glob(["Tests/**/*.swift"]),
    deps = [":BazelPostWrapper"],
)

swift_binary(
    name = "bazel_post_wrapper",
    deps = [":BazelPostWrapper"],
)

```

FWIW, this works if I use the `swift_test` as dep on `macos_unit_test` and run the `macos_unit_test` target instead.

**Comment by jpsim** [comment]
Similar to this bug that SwiftPM used to have: https://github.com/apple/swift-package-manager/issues/4639

**Comment by luispadron** [comment]
I dont believe this is an issue anymore
