### ISSUE TITLE
Cannot use `@main` with `swift_binary` `srcs`

### ISSUE THREAD

**Issue by luispadron** [bazelbuild/rules_swift#913]
## Summary

In newer versions of Swift its possible to define the main entry point using `@main`. The only requirement is the type has a `public static main()` method. 

When using `rules_swift` to build a `swift_binary` that uses `@main` we get a compilation error: 

```
example.swift:12:1: error: 'main' attribute cannot be used in a module that contains top-level code
@main
^
```

This happens when the `example.swift` is part of the `swift_binary` `srcs` attribute.

This same code works and is executable when using `swift_library` and adding it as a dep of `swift_binary`. However, if you do this then `swift_library` cannot be tested with `swift_test` because of: https://github.com/bazelbuild/rules_swift/issues/911

### Example

```swift
// example.swift

import Foundation

protocol DefinesMain {
}

extension DefinesMain {
    public static func main() {
        print("Hello, world!")
    }
}

@main
struct Entry: DefinesMain {

}
```

```python
# BUILD.bazel

swift_binary(
    name = "example",
    srcs = ["example.swift"],
)
```

**Comment by keith** [comment]
Should be fixed by https://github.com/bazelbuild/rules_swift/pull/780

**Comment by keith** [comment]
Please test with that and reopen if it's not fixed!

**Comment by luispadron** [comment]
Oh nice, let me check. Were definitely using an older `rules_swift` version

**Comment by keith** [comment]
I also literally just merged it, so you'll have to test with HEAD

**Comment by luispadron** [comment]
Thanks @keith, the fix works and am able to build and run now as expected! Requires Bazel 6.0 + rules_apple update so we can't use it just yet but nice to know its ready

**Comment by keith** [comment]
Actually I don't think rules_swift HEAD should require bazel 6.0 yet, only if you also updated rules_apple, but likely the newer rules_swift is compatible with an older rules_apple. But either way thanks for testing!

**Comment by luispadron** [comment]
So I tried this rules_apple commit (which seems required in rules_swift): `9dae4a5d37d96f6aa405ac2ad50b4421c7495e52`  

That gives me:

```
Error in transition: Invalid transition input '//command_line_option:incompatible_enable_apple_toolchain_resolution'. Cannot transition on --experimental_* or --incompatible_* options
```

Which Bazel 6.0 fixes unfortunately

**Comment by keith** [comment]
rules_swift doesn't depend on rules_apple, maybe it's just that you need an updated version of [apple_support](https://github.com/bazelbuild/apple_support/) as well

**Comment by luispadron** [comment]
Ahh thats it, it was pulling in apple_support from rules_apple. Thanks!
