### ISSUE TITLE
bazel sync fails with "Not a regular file: six.BUILD" error

### ISSUE THREAD

**Issue by Tom-Le** [bazelbuild/rules_swift#914]
When I clone this repo and run `bazel sync` with no modifications, I get the following error:

```
INFO: Repository six instantiated at:
  <snip>/rules_swift/WORKSPACE:15:31: in <toplevel>
  /private/var/tmp/<snip>/external/build_bazel_rules_swift/swift/extras.bzl:37:29: in swift_rules_extra_dependencies
  /private/var/tmp/<snip>/external/rules_proto/proto/repositories.bzl:29:14: in rules_proto_dependencies
  /private/var/tmp/<snip>/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /private/var/tmp/<snip>/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'six':
   Traceback (most recent call last):
        File "/private/var/tmp/<snip>/external/bazel_tools/tools/build_defs/repo/http.bzl", line 135, column 28, in _http_archive_impl
                workspace_and_buildfile(ctx)
        File "/private/var/tmp/<snip>/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, column 41, in workspace_and_buildfile
                ctx.file("BUILD.bazel", ctx.read(ctx.attr.build_file))
Error in read: Not a regular file: /private/var/tmp/<snip>/external/com_github_protocolbuffers_protobuf/third_party/six.BUILD
...
```

Tested with bazel version 5.3.1. Running `bazel sync` on an empty workspace that has rules_swift as an external dependency produces the same error.

I believe this is caused by swift/repositories.bzl pulling an old version of rules_proto that references the six.BUILD file mentioned above through a transitive dependency on https://github.com/protocolbuffers/protobuf. This six.BUILD file was removed in protocolbuffers/protobuf@f8a22b45, but rules_proto wasn't updated to remove references to six until bazelbuild/rules_proto@244e0b64.

**Comment by Tom-Le** [comment]
My attempt to update rules_proto to the latest version (https://github.com/bazelbuild/rules_swift/pull/915) caused some CI failures caused by "proto_common_do_not_use" not being found in rules_proto/proto/private/native.bzl. I'm not familiar enough with Bazel to figure out the root cause, and I suspect that supporting `bazel sync` is low priority anyway. Closing issue.

**Comment by keith** [comment]
Fixed by https://github.com/bazelbuild/rules_swift/pull/916, thanks for the report. In my testing I had to do a `bazel clean --expunge` after this update, but then it worked, i guess the old artifact somehow isn't handled well.
