### ISSUE TITLE
output '*-Swift.h' was not created

### ISSUE THREAD

**Issue by Ayatuas** [bazelbuild/rules_swift#921]
Hi, all.
I met some situatioins where incremental builds failed with missing output in a very simple example:

```
# BUILD
swift_library(
    name = "swiftmodule",
    srcs = ["test.swift"],
    deps = [":swiftmodule2"],
    generates_header = True,
)

swift_library(
    name = "swiftmodule2",
    srcs = ["test2.swift"],
)
```

```
# test.swift
import swiftmodule2
```
```
# test2.swift
import Foundation
```
```
# .bazelrc
build --strategy=SwiftCompile=worker
```
After built once successfully, rebuilt with modified "test2.swift"(such as comment "import Foundation") failed:

`ERROR: /Users/nathancao/xxx/BUILD:3:14: output 'swiftmodule-Swift.h' was not created`  
`ERROR:  /Users/nathancao/xxx/BUILD:3:14: Compiling Swift module //:swiftmodule failed: not all outputs were created or valid` 

Should we copy swift-generate-headers to incremental output path when generated and copy them back when compiler not produce?

My fix commit
(https://github.com/Ayatuas/rules_swift/commit/65d9bc1d41437b67c4663d0620c79d825462b574)

**Comment by keith** [comment]
oh jeez, i read the issue and didn't see you had a fix for it, I submitted https://github.com/bazelbuild/rules_swift/pull/922 which appears to be virtually the same, thanks for the detailed report!

**Comment by Ayatuas** [comment]
👍
