### ISSUE TITLE
Incremental swft compilation issue ?

### ISSUE THREAD

**Issue by QuentinPerez** [bazelbuild/rules_swift#929]
:wave:

After benchmarking vanilla xcodeproj vs bazel xcodeproj, it seems that the incremental build doesn't work as expected.
Here is a repo with the details on how to reproduce it https://github.com/QuentinPerez/rules_swift_incremental_build.

**Comment by brentleyjones** [comment]
When debugging this with @QuentinPerez the worker sometimes took the same speed as Xcode. So it seems that something is tripping up the incremental compilation.

**Comment by QuentinPerez** [comment]
is there anything that I can do to help on this issue?

**Comment by brentleyjones** [comment]
I believe the issue was not having `--features=swift.use_global_module_cache` set. We really should make that the default.

**Comment by cerisier** [comment]
Was also missing `--strategy=SwiftCompile=worker`. We don't see the issue anymore. We can close I think right @QuentinPerez ?
