### ISSUE TITLE
Not all outputs were created or valid when building for IOS device

### ISSUE THREAD

**Issue by mattdornfeld** [bazelbuild/rules_swift#934]
Cross posting from rules_spm https://github.com/cgrindel/rules_spm/issues/196

I'm trying to use rules_apple + rules_spm to build and deploy a Swift ios app to an IPhone. I'm able to build it for my laptop and run it in the IPhone simulator using this command

    bazel build :build_preview_app --apple_platform_type=ios

However when I try to build it for an IPhone device by specifying the CPU architecture 

    bazel build :build_preview_app --apple_platform_type=ios --ios_multi_cpus=arm64

I get a bunch of errors that look like this (I'm just posting a random sampling of lines). There are probably hundreds of error lines.

    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/CNIOBoringSSL.build/ssl/ssl_key_share.cc.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/CNIOBoringSSL.build/ssl/ssl_lib.cc.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/NIOTransportServices.build/NIOTSNetworkEvents.swift.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/NIOTransportServices.build/SocketAddress+NWEndpoint.swift.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/NIOTransportServices.build/StateManagedChannel.swift.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/NIOTransportServices.build/TCPOptions+SocketChannelOption.swift.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/XCTestDynamicOverlay.swiftdoc' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/XCTestDynamicOverlay.build/XCTFail.swift.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: output 'external/swift_pkgs/spm_build/arm64-apple-macosx/release/XCTestDynamicOverlay.build/XCTIsTesting.swift.o' was not created
    ERROR: /private/var/tmp/_bazel_johnsmith/bc251fba59d5612c8a8ba9752f7cffc6/external/swift_pkgs/BUILD.bazel:11155:12: Building Swift package (external/swift_pkgs) for arm64-apple-ios15.5 using SPM. failed: not all outputs were created or valid
    Target //app_ios_app:build_preview_app failed to build
    ERROR: /Users/johnsmith/projects/app/app_ios_app/BUILD:41:14 Linking app_ios_app/libbuild_app_preview_source.a failed: not all outputs were created or valid

Any idea on what might be causing the issue? For reference here's a simplified version of my BUILD file

    load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
    load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
    
    swift_library(
        name = "build_app_source",
        srcs = glob([
            "AppSource/**/*.swift",
        ]),
        deps = [
            "@swift_pkgs//Bow:Bow",
            "@swift_pkgs//Bow:BowEffects",
            "@swift_pkgs//Bow:BowOptics",
            "@swift_pkgs//Cache:Cache",
            "@swift_pkgs//swift-composable-architecture:ComposableArchitecture",
        ],
        module_name = "AppSource"
    )
    
    ios_application(
        name = "build_preview_app",
        bundle_name = "AppPreview",
        bundle_id = "co.name.AppPreview",
        families = [
            "iphone",
            "ipad",
        ],
        minimum_os_version = "15.0",
        infoplists = [":App/Info.plist"],
        visibility = ["//visibility:public"],
        deps = [
            ":build_app_source",
        ],
        provisioning_profile = "f3901410-71c1-4fe8-ab63-5c2563a07f49.mobileprovision"
    )

Here's my WORKSPACE file

    load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
    
    http_archive(
        name = "com_github_buildbuddy_io_rules_xcodeproj",
        sha256 = "564381b33261ba29e3c8f505de82fc398452700b605d785ce3e4b9dd6c73b623",
        url = "https://github.com/buildbuddy-io/rules_xcodeproj/releases/download/0.9.0/release.tar.gz",
    )
    
    http_archive(
        name = "cgrindel_rules_spm",
        sha256 = "03718eb865a100ba4449ebcbca6d97bf6ea78fa17346ce6d55532312e8bf9aa8",
        strip_prefix = "rules_spm-0.11.0",
        url = "https://github.com/cgrindel/rules_spm/archive/v0.11.0.tar.gz",
    )
    
    load(
        "@cgrindel_rules_spm//spm:defs.bzl",
        "spm_pkg",
        "spm_repositories",
        )
    
    load(
        "@cgrindel_rules_spm//spm:deps.bzl",
        "spm_rules_dependencies",
    )
    spm_rules_dependencies()
    
    load(
        "@com_github_buildbuddy_io_rules_xcodeproj//xcodeproj:repositories.bzl",
        "xcodeproj_rules_dependencies",
    )
    xcodeproj_rules_dependencies()
    
    load(
        "@build_bazel_rules_apple//apple:repositories.bzl",
        "apple_rules_dependencies",
    )
    apple_rules_dependencies()
    
    load(
        "@build_bazel_rules_swift//swift:repositories.bzl",
        "swift_rules_dependencies",
        )
    swift_rules_dependencies()
    
    load(
        "@build_bazel_rules_swift//swift:extras.bzl",
        "swift_rules_extra_dependencies",
    )
    swift_rules_extra_dependencies()
    
    load(
        "@build_bazel_apple_support//lib:repositories.bzl",
        "apple_support_dependencies",
    )
    apple_support_dependencies()
    
    spm_repositories(
        name = "swift_pkgs",
        platforms = [
            ".macOS(.v10_15)",
            ".iOS(.v15)"
        ],
        dependencies = [
            spm_pkg(
                url = "https://github.com/apple/swift-log.git",
                exact_version = "1.4.2",
                products = ["Logging"],
            ),
            spm_pkg(
                url = "https://github.com/pointfreeco/swift-composable-architecture.git",
                exact_version = "0.43.0",
                products = ["ComposableArchitecture"],
            ),
            spm_pkg(
                name = "Bow",
                url = "https://github.com/bow-swift/bow.git",
                exact_version = "0.8.0",
                products = ["Bow", "BowEffects", "BowOptics"],
            ),
            spm_pkg(
                url = "https://github.com/grpc/grpc-swift.git",
                exact_version = "1.7.3",
                products = ["GRPC"],
            ),
            spm_pkg(
                url = "https://github.com/hyperoslo/Cache",
                exact_version = "6.0.0",
                products = ["Cache"],
            ),
        ],
    )

**Comment by keith** [comment]
your other issue is the right place for this https://github.com/cgrindel/rules_spm/issues/196, it appears that the `spm_repositories` rule isn't creating the expected output files before rules_swift is even in the mix
