### ISSUE TITLE
How to use bridging headers?

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/rules_swift#94]
I have a project that uses `[project]-Bridging-Header.h` in XCode to `import` some headers. Those headers seem to become implicitly available to all Swift source files. Therefore most of them miss imports like `import Foundation`, `import UIKit`.

The good thing to do would probably be to add all imports, but I want to try and compile the project as is, without changes, is that possible?

How can one use bridging headers?

**Comment by keith** [comment]
You can try using these by manually adding the swiftc argument to the library's copts

**Comment by codesuki** [comment]
That's a great idea! I went ahead and fixed all the imports so I got it working, but I'll try the `copts` method just for the sake of trying. Thank you!
