### ISSUE TITLE
Feature Request: Implement `--test_filter` Support

### ISSUE THREAD

**Issue by cwybro** [bazelbuild/rules_swift#997]
### Description
Implement Bazel [`--test_filter`](https://bazel.build/docs/user-manual#test-filter) feature, [currently marked with a `TODO`](https://github.com/bazelbuild/rules_swift/blob/a4f17129f052062bc3084d56b9f25c8b51b855f9/tools/xctest_runner/xctest_runner.sh.template#L57).

This will allow `swift_test` consumers to limit the test scope of a target to a specific test class / method, which can be very useful for particularly large targets invoked commonly the command-line (i.e. without any Xcode conveniences).

As mentioned below, I attempted this edit myself and have it working in a consumer repository. I would be more than happy to work with maintainers to contribute this back to `bazelbuild/rules_swift`, and also add tests.

In the meantime, I'm starting with an issue, per the [contribution guide](https://github.com/bazelbuild/rules_swift/blob/master/CONTRIBUTING.md#file-or-claim-an-issue).

### Additional Context

- I've implemented `--test_filter` support in a [fork of bazelbuild/rules_swift](https://github.com/cwybro/rules_swift/commit/48ebc62c7cd83d3ddc1a1f0b79c4f245175eda15).
- I've [created a repository](https://github.com/cwybro/bazel-swift-test-filter) demonstrating the consumption of this new support (and simultaneously the missing support depending on the backing of the `build_bazel_rules_swift` `http_archive`).

**Comment by keith** [comment]
Looks good to me! Happy to merge a related PR!

**Comment by cwybro** [comment]
> Looks good to me! Happy to merge a related PR!

Thanks, @keith! Just opened https://github.com/bazelbuild/rules_swift/pull/999 -- I'll work on adding a test for this prior to upgrading from a draft.

**Comment by keith** [comment]
great! looks good so far

**Comment by keith** [comment]
https://github.com/bazelbuild/rules_swift/pull/999
